In [ ]:
import sys, os
_ROOT = os.path.abspath(os.path.join(os.getcwd(), '../..'))  # scrape_code/
sys.path.insert(0, os.path.join(_ROOT, 'scrapers'))
sys.path.insert(0, os.path.join(_ROOT, 'utils'))

## General Maintenance Notebook for the Pipeline and the database

In [1]:
import numpy as np 
import pandas as pd 
from scraper import scrape_model 
import os, sys, time
import requests 
import datetime, dateparser

from bs4 import BeautifulSoup
from tqdm import tqdm


from selenium import webdriver 
from selenium.webdriver.chrome.options import Options 
from selenium.webdriver.common.by import By 
from selenium.common.exceptions import NoSuchElementException, WebDriverException
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from util_data_funcs import *


def close_out_driver(wd):
    wd.close()
    wd.quit()


headers = {
    'User-Agent': 
           'Mozilla/5.0 (X11; Linux x86_64)'+\
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
}


def parse_game_date(date_parse):    
    hour = date_parse[:date_parse.find(':')]
    minute = date_parse[date_parse.find(':')+1:date_parse.find(' ')]
    am_pm = date_parse[date_parse.find(' ')+1:date_parse.find(',')]

    month_day = date_parse[date_parse.find(',')+2:-6]
    month, day = datetime.datetime(month_day.split(' ')[0], '%b').month , month_day.split(' ')[1]
    # year = date_parse[-4:]

    return datetime.date(int(month), int(day))


def parse_game_date_v2(date_parse):
    dow = date_parse[:date_parse.find(',')]
    month = date_parse[date_parse.find(',')+2:date_parse.find(',')+5]
    month_num = datetime.datetime.strptime(month, '%b').month
    dom = date_parse[date_parse.find(month)+4:]
    return (int(month_num), int(dom))


def parse_game_date_v3(df):
    fr_parse = dateparser.parse(df['date'], languages=['fr'])
    es_parse = dateparser.parse(df['date'], languages=['es'])
    en_parse = dateparser.parse(df['date'], languages=['en'])

    if fr_parse == None:
        if es_parse == None:
            # print(df['date'])
            return en_parse.date().replace(year=df['season'])
        else:
            return es_parse.date().replace(year=df['season'])
    else:
        return fr_parse.date().replace(year=df['season'])


sched_path = 'formed_data/game_schedule_data'
sched_file_dir = os.listdir(sched_path)
urc_sched_files = [sched_path + '/' + i for i in sched_file_dir if 'URC_' in i]
prem_sched_files = [sched_path + '/' + i for i in sched_file_dir if 'Prem_' in i]
sr_sched_files = [sched_path + '/' + i for i in sched_file_dir if 'SR_' in i]
t14_sched_files = [sched_path + '/' + i for i in sched_file_dir if 'T14_' in i]
champ_cup_sched_files = [sched_path + '/' + i for i in sched_file_dir if 'ChampCup' in i]

six_nations_sched_files = [sched_path + '/' + i for i in sched_file_dir if 'SixNat_' in i]
rchamp_sched_files = [sched_path + '/' + i for i in sched_file_dir if 'RChamp_' in i]



game_path = 'formed_data/game_data'
game_file_dir = os.listdir(game_path)
urc_game_files = [game_path + '/' + i for i in game_file_dir if 'URC_' in i]
prem_game_files = [game_path + '/' + i for i in game_file_dir if 'Prem_' in i]
sr_game_files = [game_path + '/' + i for i in game_file_dir if 'SR_' in i]
t14_game_files = [game_path + '/' + i for i in game_file_dir if 'T14_' in i]
champ_cup_game_files = [game_path + '/' + i for i in game_file_dir if 'ChampCup_' in i]

six_nations_game_files = [game_path + '/' + i for i in game_file_dir if 'SixNat_' in i]
rchamp_game_files = [game_path + '/' + i for i in game_file_dir if 'RChamp_' in i]



t14_game_df, t14_player_df, t14_team_df = gather_dataframes('T14')
urc_game_df, urc_player_df, urc_team_df = gather_dataframes('URC')
prem_game_df, prem_player_df, prem_team_df = gather_dataframes('Prem')
champ_cup_game_df, champ_cup_player_df = gather_dataframes('ChampCup')

# sr_game_df, sr_player_df, sr_team_df = gather_dataframes('SR')
six_nat_game_df, six_nat_player_df, six_nat_team_df = gather_dataframes('SixNat')

# rchamp_game_df, rchamp_player_df, rchamp_team_df = gather_dataframes('RChamp')

/home/colingrosh/Desktop/sports_analytics/code/rugby_v2/Rugby_DB_Analysis/scrape_code/util_data_funcs.py:56: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  grab_files = lambda league, order: pd.concat(list(map(pd.read_csv, league_dict[league][order])))
/home/colingrosh/Desktop/sports_analytics/code/rugby_v2/Rugby_DB_Analysis/scrape_code/util_data_funcs.py:56: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  grab_files = lambda league, order: pd.concat(list(map(pd.read_csv, league_dict[league][order])))

### Checking the number of Games in each league season and comparing to the games that I have pulled so far

In [2]:
# Util function used in schedule pulls 
def label_table_parse(labels, table):
    row_step = []
    for row in table:
        val_text = row.text
        if val_text not in labels:
            row_step.append(val_text)

    row_ordered = [[row_step[i-1], row_step[i]] \
                    for i in range(1, len(row_step), 2)]

    return row_ordered 

# Takes the game and league to parse the match stats 
def get_match_stats(game_id, league_id): 

    # URL declaration, scraping, and initial parsing to get the tables on the page 
    url = 'https://www.espn.co.uk/rugby/matchstats/_/gameId/{}/league/{}'.format(
        game_id, league_id
    )
    response = requests.get(url, headers=headers).content
    soup = BeautifulSoup(response, 'html.parser')
    tables = soup.find_all('table')

    nav_bar_items = soup.find_all('nav')

    # Group labels 
    group_2_labels = ['Tries', 'Conversion Goals', 
                        'Penalty Goals', 'Kick Percent Success'
    ]
    group_3_labels = ['Kicks From Hand', 'Passes', 'Runs']
    group_4_labels = [
        'Possession 1H/2H', 'Territory 1H/2H', 'Clean Breaks', 
        'Defenders Beaten', 'Offload', 'Rucks Won', 
        'Mauls Won', 'Turnovers Conceded'
    ]
    group_8_labels = ['Red Cards', 'Yellow Cards', 'Total Free Kicks Conceded']

    # Parsed data lists used by multiple groups 
    four_tables = soup.find_all(
        class_='sub-module equal-height countChartList height-reset'
    )
    check_top_largeLabels = soup.find_all(
        class_="stat-graph compareLineGraph twoTeam largeLabels"
    )
    stacked_rls = soup.find_all(class_='stacked-rl')

    # GROUP 1: Home and Away team parsing 
    top_bar = soup.find(class_='competitors')

    h_a_team_bar = [
        top_bar.find(class_='team team-a'),
        top_bar.find(class_='team team-b')
    ]

    # GROUP 2: Match Events 
    match_event = four_tables[0].find('tbody')
    match_event_rows = match_event.find_all('td')

    group_2_ordered = label_table_parse(group_2_labels, match_event_rows)

    # GROUP 3: Kick/Pass/Run 
    home_away_total_meters = [
        int(i.text) for i in check_top_largeLabels[0].find_all(class_='chartValue')
    ]

    meter_rows = four_tables[1].find('tbody').find_all('td')
    group_3_ordered = label_table_parse(group_3_labels, meter_rows)

    # GROUP 4: Attacking 
    attack_rows = stacked_rls[0].find('tbody').find_all('td')
    group_4_ordered = label_table_parse(group_4_labels, attack_rows)

    # GROUP 5: Possession and Territory 
    terr_vals = soup.find_all(
        class_="stat-graph compareLineGraph twoTeam largeLabels large"
    )[0].find_all(class_='chartValue')

    poss_vals = check_top_largeLabels[1].find_all(class_='chartValue')

    # GROUP 6: Set Pieces 
    sp_charts = four_tables[2].find_all(class_='countChart')

    # list of scrums and then lineouts. 00 is home scrums, 10 is home lineouts 
    h_a_set_pieces = [
        [
            sp_charts[0].find_all(class_='countLabel')[0].text,
            sp_charts[0].find_all(class_='countLabel')[1].text
        ],
        [
            sp_charts[1].find_all(class_='countLabel')[0].text,
            sp_charts[1].find_all(class_='countLabel')[1].text
        ]
    ]

    # GROUP 7: Defending 
    # list of lists, raw tackles and then home tackles 
    tackles = [
        four_tables[3].find_all(class_='home-team'),
        four_tables[3].find_all(class_='away-team')
    ]

    # GROUP 8: Discipline and Penalties 
    disc_rows = tables[3].find('tbody').find_all('td')
    penalty = stacked_rls[1].find(class_='countChart').find_all(
        class_='countLabel'
    )

    group_8_ordered = label_table_parse(group_8_labels, disc_rows)

    # Combine all group variables 
    top_data_dict = {
        'game_id': game_id,
        'league_id': league_id,

        # GROUP 1 metrics 
        'home_team': h_a_team_bar[0].find(class_='short-name').text,
        'home_team_score': int(h_a_team_bar[0].find(class_='score-container').text), 
        'away_team': h_a_team_bar[1].find(class_='short-name').text,
        'away_team_score': int(h_a_team_bar[1].find(class_='score-container').text),

        # GROUP 2 metrics 
        'home_tries': group_2_ordered[0][0],
        'away_tries': group_2_ordered[0][1],
        'home_conversions': group_2_ordered[1][0],
        'away_conversions': group_2_ordered[1][1],
        'home_penalty_goals': group_2_ordered[2][0],
        'away_penalty_goals': group_2_ordered[2][1],
        'home_kick_percent': group_2_ordered[3][0],
        'away_kick_percent': group_2_ordered[3][1],

        # GROUP 3 metrics 
        'home_total_meters': home_away_total_meters[0],
        'away_total_meters': home_away_total_meters[1],
        'home_kfh': group_3_ordered[0][0],
        'away_kfh': group_3_ordered[0][1],
        'home_pass_meters': group_3_ordered[1][0],
        'away_pass_meters': group_3_ordered[1][1],
        'home_runs': group_3_ordered[2][0],
        'away_runs': group_3_ordered[2][1],

        # GROUP 4 metrics 
        'home_possession_1h_2h': group_4_ordered[0][0],
        'home_territory_1h_2h': group_4_ordered[1][0],
        'home_clean_breaks': group_4_ordered[2][0],
        'home_defenders_beaten': group_4_ordered[3][0],
        'home_offloads': group_4_ordered[4][0],
        'home_rucks_won': group_4_ordered[5][0],
        'home_mauls_won': group_4_ordered[6][0],
        'home_turnovers_conceeded': group_4_ordered[7][0],
        'away_possession_1h_2h': group_4_ordered[0][1],
        'away_territory_1h_2h': group_4_ordered[1][1],
        'away_clean_breaks': group_4_ordered[2][1],
        'away_defenders_beaten': group_4_ordered[3][1],
        'away_offloads': group_4_ordered[4][1],
        'away_rucks_won': group_4_ordered[5][1],
        'away_mauls_won': group_4_ordered[6][1],
        'away_turnovers_conceeded': group_4_ordered[7][1],

        # GROUP 5 metrics 
        'home_total_possession': poss_vals[0].text,
        'home_total_territory': terr_vals[0].text,
        'away_total_possesion': poss_vals[1].text,
        'away_total_territory': terr_vals[1].text,

        # GROUP 6 metrics 
        'home_scrum': h_a_set_pieces[0][0],
        'home_lineout': h_a_set_pieces[1][0],
        'away_scrum': h_a_set_pieces[0][1],
        'away_lineout': h_a_set_pieces[1][1],

        # GROUP 7 metrics 
        'home_tackles': tackles[0][0].text, 
        'home_tackle_perc': tackles[1][0].text, 
        'away_tackles': tackles[0][1].text, 
        'away_tackle_perc': tackles[1][1].text,

        # GROUP 8 metrics 
        'home_red_cards': group_8_ordered[0][0],
        'home_yellow_cards': group_8_ordered[1][0],
        'home_free_kicks_con': group_8_ordered[2][0], 
        'away_red_cards': group_8_ordered[0][1],
        'away_yellow_cards': group_8_ordered[1][1],
        'away_free_kicks_con': group_8_ordered[2][1],
        'home_penalties': int(penalty[0].text),
        'away_penalties': int(penalty[1].text)

    }

    df = pd.DataFrame(top_data_dict, index=[0])
    
    return df, nav_bar_items

# Functions below are used for gathering team and league data based on the inputs to the class 
def get_teams_list(season, league):
    
    test_url = 'https://www.espn.co.uk' + \
        '/rugby/table/_/league/{}/season/{}'.format(league, season)
    response = requests.get(test_url, headers=headers).content
    soup_team = BeautifulSoup(response, 'html.parser')

    get_index = lambda x, char: x.find(char)

    tbodies = soup_team.find_all('tbody')
    if len(tbodies) > 1:
        tbodies = tbodies[::2]

    team_name_link = {}
    for tbody in tbodies:

        row_trs = tbody.find_all('tr')

        for tr in row_trs:
            # print(tr.text)
            td_start = tr.find_all('td')[0]
            try:
                team_link = td_start.find_all('a')[0]['href']
                # print(team_link)
                # team_name_link[td_start.find_all('a')[1].find('span').text] = [
                # team_name_link[td_start.find_all('a')[2].text] = [
                team_name_link[td_start.find_all('a')[-1].text] = [
                    team_link,
                    team_link[team_link.find('id/')+3:team_link.find('id/')+3+\
                                get_index(team_link[team_link.find('id/')+3:], '/')]
                ]
            except:
                print(tr)
                team_link = None 
                team_name_link[td_start.find_all('a')[2].text] = [
                    team_link,
                    None
                ]

    return team_name_link 
        

def get_schedule(teams_list, league, season, team_input = None):
    
    if len(teams_list.keys()) == 0:
        sched_dict = {}
        
    elif team_input is not None:
        results_base_url = "https://www.espn.co.uk/rugby/results/_/team/"
        team_id = teams_list[team][1]

        team_page_resp = requests.get(
            results_base_url+team_id+'/league/{}/season/{}'.format(league, season), \
            headers=headers).content
        team_soup = BeautifulSoup(team_page_resp, 'html.parser')
        
        full_sched = team_soup.find(id='sched-container')
        match_months = full_sched.find_all('tbody')
    
    else:
        sched_dict = {}

        results_base_url = "https://www.espn.co.uk/rugby/results/_/team/"
        for team in teams_list.keys():
            team_id = teams_list[team][1]
            if team_id is not None:

                team_page_resp = requests.get(
                    results_base_url+team_id+'/league/{}/season/{}'.format(league, season),
                    headers=headers).content
                team_soup = BeautifulSoup(team_page_resp, 'html.parser')

                full_sched = team_soup.find(id='sched-container')
                match_months = full_sched.find_all('tbody')

                sched_dict[team] = match_months 

    return sched_dict


def parse_scheds(sched):
    
    totals = []
    for mon in sched:

        rows = mon.find_all('tr')

        for row in rows:

            first_row = row.find_all('td')
            date = first_row[0].text

            home_base, away_base = first_row[1].find_all('a')[0], \
                    first_row[2].find_all('a')[0]

            home_team, away_team = home_base.find('span').text, \
                    away_base.find('span').text

            home_team_abbr, away_team_abbr = home_base.find('abbr').text, \
                    away_base.find('abbr').text

            try:
                game_link = first_row[1].find_all('span')[-1].find('a')['href']
                game_id, league_id = game_link[
                    game_link.find('Id/')+3:game_link.find('/league')], \
                game_link[game_link.find('league/')+7:]
                score = first_row[1].find_all('span')[-1].find('a').text

            except TypeError:
                game_link, game_id, league_id = np.nan, np.nan, np.nan 
                score = first_row[1].find_all('span')[-1].text
    
            competition, stadium = first_row[4].text, first_row[5].text
            home_score, away_score = score.split()[0], score.split()[-1]

            totals.append([
                date, home_team, away_team, home_team_abbr,
                away_team_abbr, game_link, score, home_score,
                away_score, competition, stadium, game_id, league_id
            ])

    comb_df = pd.DataFrame(
        totals,
        columns=[
            'date', 'home_team', 'away_team', 
            'home_team_abbr', 'away_team_abbr', 'game_link', 
            'score', 'home_score', 'away_score', 
            'competition', 'stadium', 'game_id', 'league_id']
    )

    return comb_df

In [3]:
df, nav_bar_items = get_match_stats(602502, 180659)

In [3]:
champ_cup_league = 271937
chall_cup_league = 272073
season_test_cc = 2021 

team_links_cc = get_teams_list(season_test_cc, champ_cup_league)
team_links_cc

{'Leinster': ['/rugby/team/_/id/25924/leinster', '25924'],
 'Wasps': ['/rugby/team/_/id/25905/wasps', '25905'],
 'Bordeaux Begles': ['/rugby/team/_/id/143737/bordeaux-begles', '143737'],
 'La Rochelle': ['/rugby/team/_/id/119318/la-rochelle', '119318'],
 'Scarlets': ['/rugby/team/_/id/25966/scarlets', '25966'],
 'Edinburgh': ['/rugby/team/_/id/25951/edinburgh', '25951'],
 'Toulon': ['/rugby/team/_/id/25986/toulon', '25986'],
 'Sale Sharks': ['/rugby/team/_/id/25908/sale-sharks', '25908'],
 'Northampton Saints': ['/rugby/team/_/id/25907/northampton-saints', '25907'],
 'Bath Rugby': ['/rugby/team/_/id/25898/bath-rugby', '25898'],
 'Montpellier Herault': ['/rugby/team/_/id/25918/montpellier-herault',
  '25918'],
 'Dragons': ['/rugby/team/_/id/25967/dragons', '25967'],
 'Lyon': ['/rugby/team/_/id/143736/lyon', '143736'],
 'Racing 92': ['/rugby/team/_/id/99855/racing-92', '99855'],
 'Stade Toulousain': ['/rugby/team/_/id/25922/stade-toulousain', '25922'],
 'Munster': ['/rugby/team/_/id/25925/munster', '25925'],
 'Clermont Auvergne': ['/rugby/team/_/id/25917/clermont-auvergne', '25917'],
 'Bristol Rugby': ['/rugby/team/_/id/25899/bristol-rugby', '25899'],
 'Exeter Chiefs': ['/rugby/team/_/id/116227/exeter-chiefs', '116227'],
 'Gloucester Rugby': ['/rugby/team/_/id/25900/gloucester-rugby', '25900'],
 'Ulster': ['/rugby/team/_/id/25926/ulster', '25926'],
 'Connacht': ['/rugby/team/_/id/25923/connacht', '25923'],
 'Harlequins': ['/rugby/team/_/id/25901/harlequins', '25901'],
 'Glasgow Warriors': ['/rugby/team/_/id/25952/glasgow-warriors', '25952']}

In [5]:
len(team_links_cc)

24

In [3]:
season_test = 2021
league_test = 270557

team_links = get_teams_list(season_test, league_test)
team_sched = get_schedule(
    teams_list=team_links,
    league=league_test,
    season=season_test
)

### Gathering the Time of Game in which Red Card or Yellow card was given out

In [2]:
# options = webdriver.ChromeOptions()
# driver = webdriver.Chrome(options=options)

In [2]:
total_club_df = pd.concat(
    [urc_game_df, t14_game_df, prem_game_df, champ_cup_game_df]
)



# total_club_df = format_score_diff_feats(total_club_df)

In [4]:
rc_games = total_club_df[total_club_df['home_red_cards'] >= 1]

In [5]:
# from bs4 import BeautifulSoup

# game_check = 598075
# league_check = 270557

# URL declaration, scraping, and initial parsing to get the tables on the page 
# url = 'https://www.espn.com/rugby/commentary/_/gameId/{}/league/{}'.format(
#     game_check, league_check
# )
# response = requests.get(url, headers=headers).content
# soup = BeautifulSoup(response, 'html.parser')

In [3]:
def grab_match_comms_cards(game, league):
    # URL declaration, scraping, and initial parsing to get the tables on the page 
    url = 'https://www.espn.com/rugby/commentary/_/gameId/{}/league/{}'.format(
        game, league
    )
    response = requests.get(url, headers=headers).content
    soup = BeautifulSoup(response, 'html.parser')

    comm_table = soup.find_all('tbody')[4]
    table_rows = [i.find_all('td') for i in comm_table.find_all('tr')]

    base_data = []
    for row in table_rows:
        row_dict = {
            'game_id': game,
            'league_id': league,
            'Time': None,
            'Team': None,
            'Player': None,
            'Event_Type': None,
            'Home_Score': None, 
            'Away_Score': None
        }

        if '+' in row[0].text:
            time_base = int(row[0].text.split("'")[0])
            time_end = int(row[0].text.split('+')[1])
            row_dict['Time'] = time_base + time_end
        else:
            row_dict['Time'] = int(row[0].text[:-1])

        event_desc = row[-1].text
        if 'Red card' in event_desc:
            row_dict['Event_Type'] = 'Red_Card'
            row_dict['Player'] = event_desc[event_desc.find('card -')+7:event_desc.find(',')-1]

        elif 'Yellow card' in event_desc:
            row_dict['Event_Type'] = 'Yellow_Card'
            row_dict['Player'] = event_desc[event_desc.find('card -')+7:event_desc.find(',')-1]

        elif 'Conversion -' in event_desc:
            row_dict['Event_Type'] = 'Conversion'
            row_dict['Player'] = event_desc[event_desc.find('Conversion -')+13:event_desc.find(',')-1]

        elif 'Try -' in event_desc:
            row_dict['Event_Type'] = 'Try'
            row_dict['Player'] = event_desc[event_desc.find('Try -')+6:event_desc.find(',')-1]

        elif 'Penalty goal -' in event_desc:
            row_dict['Event_Type'] = 'Penalty_Goal'
            row_dict['Player'] = event_desc[event_desc.find('goal -')+7:event_desc.find(',')-1]

        elif 'Substitute on' in event_desc:
            row_dict['Event_Type'] = 'Sub_In'
            row_dict['Player'] = event_desc[event_desc.find('on -')+5:event_desc.find(',')-1]

        elif 'Player substituted' in event_desc:
            row_dict['Event_Type'] = 'Sub_Out'
            row_dict['Player'] = event_desc[event_desc.find('tuted -')+8:event_desc.find(',')-1]
        
        else:
            # print('here')
            continue
            # print('now_here')

        if row_dict['Event_Type'] in ['Try', 'Penalty_Goal', 'Conversion']:
            scores = event_desc.split(' ')[0].split('-')
            row_dict['Home_Score'] = int(scores[0])
            row_dict['Away_Score'] = int(scores[1])
        
        row_dict['Team'] = event_desc[event_desc.find(',')+2:]
        base_data.append(row_dict)
    
    df = pd.DataFrame(base_data)
    df['Home_Score'] = df['Home_Score'].bfill()
    df['Away_Score'] = df['Away_Score'].bfill()

    return df

In [10]:
game = 191369
league = 270557

# URL declaration, scraping, and initial parsing to get the tables on the page 
url = 'https://www.espn.com/rugby/commentary/_/gameId/{}/league/{}'.format(
    game, league
)
response = requests.get(url, headers=headers).content
soup = BeautifulSoup(response, 'html.parser')

comm_table = soup.find_all('tbody')[4]
table_rows = [i.find_all('td') for i in comm_table.find_all('tr')]

In [12]:
table_rows[0][-1].text

'12-17 End of second half'

In [16]:
grab_match_comms_cards(191369, 270557)

here
here
here
here

,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score
0,191369,270557,79,Glasgow Warriors,Mark Bennett,Sub_Out,12.0,17.0
1,191369,270557,79,Glasgow Warriors,Scott Wight,Sub_In,12.0,17.0
2,191369,270557,79,Scarlets,Adam Warren,Sub_In,12.0,17.0
3,191369,270557,79,Scarlets,Gareth Maule,Sub_Out,12.0,17.0
4,191369,270557,76,Scarlets,Aled Davies,Sub_In,12.0,17.0
5,191369,270557,76,Scarlets,Rhodri Williams,Sub_Out,12.0,17.0
6,191369,270557,75,Glasgow Warriors,Nikola Matawalu,Yellow_Card,12.0,17.0
7,191369,270557,75,Scarlets,Jacobie Adriaanse,Sub_Out,12.0,17.0
8,191369,270557,75,Scarlets,Rhodri Jones,Sub_In,12.0,17.0
9,191369,270557,73,Scarlets,Rhodri Jones,Sub_Out,12.0,17.0
10,191369,270557,73,Scarlets,Josh Turnbull,Sub_In,12.0,17.0
11,191369,270557,68,Scarlets,Josh Turnbull,Sub_Out,12.0,17.0
12,191369,270557,68,Scarlets,Rhodri Jones,Sub_In,12.0,17.0
13,191369,270557,68,Glasgow Warriors,Jerry Yanuyanutawa,Sub_In,12.0,17.0
14,191369,270557,68,Glasgow Warriors,Ryan Grant,Sub_Out,12.0,17.0
15,191369,270557,68,Glasgow Warriors,Pat MacArthur,Sub_Out,12.0,17.0
16,191369,270557,68,Glasgow Warriors,Fraser Brown,Sub_In,12.0,17.0
17,191369,270557,68,Glasgow Warriors,James Eddie,Sub_In,12.0,17.0
18,191369,270557,68,Glasgow Warriors,Rob Harley,Sub_Out,12.0,17.0
19,191369,270557,64,Glasgow Warriors,Chris Cusiter,Sub_Out,12.0,17.0
20,191369,270557,64,Glasgow Warriors,DTH Van Der Merwe,Sub_In,12.0,17.0
21,191369,270557,62,Glasgow Warriors,Duncan Weir,Penalty_Goal,12.0,17.0
22,191369,270557,60,Scarlets,Jordan Williams,Penalty_Goal,12.0,14.0
23,191369,270557,60,Scarlets,Rob Evans,Sub_In,9.0,14.0
24,191369,270557,60,Scarlets,Phil John,Sub_Out,9.0,14.0
25,191369,270557,53,Scarlets,Johan Snyman,Sub_Out,9.0,14.0
26,191369,270557,53,Scarlets,Jake Ball,Sub_In,9.0,14.0
27,191369,270557,49,Glasgow Warriors,Jon Welsh,Sub_In,9.0,14.0
28,191369,270557,49,Glasgow Warriors,Moray Low,Sub_Out,9.0,14.0
29,191369,270557,49,Glasgow Warriors,Richie Vernon,Sub_Out,9.0,14.0
30,191369,270557,49,Glasgow Warriors,Adam Ashe,Sub_In,9.0,14.0
31,191369,270557,48,Glasgow Warriors,Sean Lamont,Yellow_Card,9.0,14.0
32,191369,270557,42,Scarlets,Rhys Priestland,Penalty_Goal,9.0,14.0
33,191369,270557,42,Scarlets,Emyr Phillips,Sub_In,6.0,14.0
34,191369,270557,42,Scarlets,Ken Owens,Sub_Out,6.0,14.0
35,191369,270557,38,Scarlets,Rhys Priestland,Penalty_Goal,6.0,14.0
36,191369,270557,32,Glasgow Warriors,Duncan Weir,Conversion,3.0,14.0
37,191369,270557,30,Glasgow Warriors,Tim Swinson,Try,3.0,12.0
38,191369,270557,30,Scarlets,Rob McCusker,Sub_Out,3.0,7.0
39,191369,270557,30,Scarlets,Aaron Shingler,Sub_In,3.0,7.0
40,191369,270557,17,Scarlets,Rhys Priestland,Penalty_Goal,3.0,7.0
41,191369,270557,5,Glasgow Warriors,Duncan Weir,Conversion,0.0,7.0
42,191369,270557,4,Glasgow Warriors,Ryan Grant,Try,0.0,5.0

In [4]:
 
input_df = total_club_df[['game_id', 'league_id', 'season']]

league_ids = [270557, 267979, 270559, 271937]
league_names = ['URC', 'Prem', 'T14', 'ChampCup']
league_index = 1



error_games = []

filt_df = input_df[input_df['league_id'] == league_ids[league_index]].reset_index(drop=True)
league_name = league_names[league_index]

base_dfs = []
for i in tqdm(range(len(filt_df))):
    try:
        game_df = grab_match_comms_cards(filt_df['game_id'].iloc[i], filt_df['league_id'].iloc[i])
        base_dfs.append(game_df)
    except: 
        error_games.append(filt_df['game_id'].iloc[i])
        continue

all_df = pd.concat(base_dfs, axis=0)
print("Missed games amount: {}".format(len(error_games)))

100%|██████████| 1741/1741 [14:07<00:00,  2.05it/s]

Missed games amount: 16

In [5]:
total_club_df[total_club_df['game_id'].isin(error_games)][['game_id', 'league_id', 'season']]

     game_id  league_id  season
20    593898     267979    2021
72    593956     267979    2022
73    593950     267979    2022
88    593959     267979    2022
110   593964     267979    2022
111   593958     267979    2022
112   593952     267979    2022
121   593957     267979    2022
122   593953     267979    2022
129   593955     267979    2022
137   593954     267979    2022
147   593904     267979    2022
37    294986     267979    2020
56    593738     267979    2021
111   290077     267979    2017
11    597080     267979    2023

In [12]:
total_club_df[(total_club_df['game_id'].isin(error_games)) & (total_club_df['season'] == 2022)]

,game_id,league_id,home_team,home_team_score,away_team,away_team_score,home_tries,away_tries,home_conversions,away_conversions,...,away_mauls_won_total_num,away_mauls_won_percent,away_scrum_num,away_scrum_total_num,away_scrum_won_percent,away_lineout_num,away_lineout_total_num,away_lineout_won_percent,date_formatted,league_season
24,598964,271937,Racing 92,13,La Rochelle,20,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-05-15,2021-2022
25,598962,271937,Racing 92,41,Sale Sharks,22,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-05-08,2021-2022
26,598958,271937,Racing 92,33,Stade Francais Paris,22,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-17,2021-2022
27,598947,271937,Stade Francais Paris,9,Racing 92,22,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-09,2021-2022
28,598940,271937,Racing 92,28,Northampton Saints,0,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-23,2021-2022
29,598922,271937,Ospreys,10,Racing 92,25,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-15,2021-2022
30,598957,271937,Ulster,23,Stade Toulousain,30,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-16,2021-2022
31,598946,271937,Stade Toulousain,20,Ulster,26,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-09,2021-2022
32,598935,271937,Ulster,34,Clermont Auvergne,31,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-22,2021-2022
33,598928,271937,Northampton Saints,20,Ulster,24,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-16,2021-2022
34,598965,271937,Leinster,21,La Rochelle,24,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-05-28,2021-2022
35,598963,271937,Leinster,40,Stade Toulousain,17,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-05-14,2021-2022
36,598960,271937,Leicester Tigers,14,Leinster,23,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-05-07,2021-2022
37,598951,271937,Leinster,56,Connacht,20,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-15,2021-2022
38,598943,271937,Connacht,21,Leinster,26,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-08,2021-2022
39,598932,271937,Bath Rugby,7,Leinster,64,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-22,2021-2022
40,598927,271937,Leinster,89,Montpellier Herault,7,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-16,2021-2022
41,598961,271937,La Rochelle,31,Montpellier Herault,19,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-05-07,2021-2022
42,598954,271937,La Rochelle,31,Bordeaux Begles,23,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-16,2021-2022
43,598944,271937,Bordeaux Begles,13,La Rochelle,31,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-09,2021-2022
44,598937,271937,Glasgow Warriors,30,La Rochelle,38,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-22,2021-2022
45,598937,271937,Glasgow Warriors,30,La Rochelle,38,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-22,2021-2022
46,598924,271937,La Rochelle,39,Bath Rugby,21,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-15,2021-2022
47,598955,271937,Munster,26,Exeter Chiefs,10,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-16,2021-2022
48,598948,271937,Exeter Chiefs,13,Munster,8,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-09,2021-2022
49,598942,271937,Montpellier Herault,37,Exeter Chiefs,26,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-23,2021-2022
50,598925,271937,Exeter Chiefs,52,Glasgow Warriors,17,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-15,2021-2022
51,598925,271937,Exeter Chiefs,52,Glasgow Warriors,17,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-15,2021-2022
52,598952,271937,Bristol Rugby,29,Sale Sharks,35,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-15,2021-2022
53,598945,271937,Sale Sharks,9,Bristol Rugby,10,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-09,2021-2022
54,598938,271937,Sale Sharks,49,Ospreys,10,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-23,2021-2022
55,598930,271937,Clermont Auvergne,25,Sale Sharks,19,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-16,2021-2022
56,598953,271937,Harlequins,33,Montpellier Herault,20,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-16,2021-2022
57,598949,271937,Montpellier Herault,40,Harlequins,26,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-10,2021-2022
58,598956,271937,Leicester Tigers,27,Clermont Auvergne,17,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-16,2021-2022
59,598950,271937,Clermont Auvergne,10,Leicester Tigers,29,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-04-10,2021-2022
60,598934,271937,Leicester Tigers,28,Bordeaux Begles,0,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-22,2021-2022
61,598923,271937,Connacht,28,Leicester Tigers,29,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-15,2021-2022
62,598931,271937,Harlequins,36,Castres Olympique,33,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-21,2021-2022
63,598920,271937,Cardiff Blues,33,Harlequins,36,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-14,2021-2022
64,598959,271937,Munster,24,Stade Toulousain,24,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-05-07,2021-2022
65,598941,271937,Munster,45,Wasps,7,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-23,2021-2022
66,598919,271937,Castres Olympique,13,Munster,16,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-14,2021-2022
67,598936,271937,Scarlets,21,Bristol Rugby,52,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-22,2021-2022
68,598926,271937,Bristol Rugby,28,Stade Francais Paris,17,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-15,2021-2022
69,598939,271937,Stade Francais Paris,37,Connacht,31,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-23,2021-2022
70,598933,271937,Stade Toulousain,0,Cardiff Blues,28,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-22,2021-2022
71,598929,271937,Bordeaux Begles,45,Scarlets,10,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-16,2021-2022
72,598921,271937,Wasps,30,Stade Toulousain,22,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-15,2021-2022

In [6]:
error_games

[np.int64(598907),
 np.int64(598895),
 np.int64(598917),
 np.int64(598905),
 np.int64(598915),
 np.int64(598896),
 np.int64(598909),
 np.int64(598904),
 np.int64(598900),
 np.int64(598911),
 np.int64(598902),
 np.int64(598908),
 np.int64(598890),
 np.int64(598901),
 np.int64(598913),
 np.int64(598893),
 np.int64(598914),
 np.int64(598898),
 np.int64(598918),
 np.int64(598912),
 np.int64(598916),
 np.int64(598903),
 np.int64(598910),
 np.int64(598906),
 np.int64(598964),
 np.int64(598962),
 np.int64(598958),
 np.int64(598947),
 np.int64(598940),
 np.int64(598922),
 np.int64(598957),
 np.int64(598946),
 np.int64(598935),
 np.int64(598928),
 np.int64(598965),
 np.int64(598963),
 np.int64(598960),
 np.int64(598951),
 np.int64(598943),
 np.int64(598932),
 np.int64(598927),
 np.int64(598961),
 np.int64(598954),
 np.int64(598944),
 np.int64(598937),
 np.int64(598937),
 np.int64(598924),
 np.int64(598955),
 np.int64(598948),
 np.int64(598942),
 np.int64(598925),
 np.int64(598925),
 np.int64(598952),
 np.int64(598945),
 np.int64(598938),
 np.int64(598930),
 np.int64(598953),
 np.int64(598949),
 np.int64(598956),
 np.int64(598950),
 np.int64(598934),
 np.int64(598923),
 np.int64(598931),
 np.int64(598920),
 np.int64(598959),
 np.int64(598941),
 np.int64(598919),
 np.int64(598936),
 np.int64(598926),
 np.int64(598939),
 np.int64(598933),
 np.int64(598929),
 np.int64(598921),
 np.int64(598846),
 np.int64(598837),
 np.int64(598832),
 np.int64(598847),
 np.int64(598840),
 np.int64(598853),
 np.int64(598842),
 np.int64(598849),
 np.int64(598839),
 np.int64(598852),
 np.int64(598836),
 np.int64(598850),
 np.int64(598834),
 np.int64(598848),
 np.int64(598833),
 np.int64(598854),
 np.int64(598843),
 np.int64(598835),
 np.int64(598841),
 np.int64(598845),
 np.int64(598855),
 np.int64(598897),
 np.int64(598889),
 np.int64(598880),
 np.int64(598868),
 np.int64(598856),
 np.int64(598882),
 np.int64(598875),
 np.int64(598863),
 np.int64(598894),
 np.int64(598891),
 np.int64(598886),
 np.int64(598871),
 np.int64(598866),
 np.int64(598899),
 np.int64(598888),
 np.int64(598881),
 np.int64(598873),
 np.int64(598864),
 np.int64(598887),
 np.int64(598870),
 np.int64(598857),
 np.int64(598885),
 np.int64(598861),
 np.int64(598869),
 np.int64(598884),
 np.int64(598877),
 np.int64(598859),
 np.int64(598876),
 np.int64(598865),
 np.int64(598892),
 np.int64(598883),
 np.int64(598878),
 np.int64(598860),
 np.int64(598874),
 np.int64(598862),
 np.int64(598872),
 np.int64(598867),
 np.int64(598879),
 np.int64(598858)]

In [ ]:
filt_df

In [7]:
total_club_df[total_club_df['game_id'].isin(error_games)]

Empty DataFrame
Columns: [game_id, league_id, home_team, home_team_score, away_team, away_team_score, home_tries, away_tries, home_conversions, away_conversions, home_penalty_goals, away_penalty_goals, home_kick_percent, away_kick_percent, home_total_meters, away_total_meters, home_kfh, away_kfh, home_pass_meters, away_pass_meters, home_runs, away_runs, home_possession_1h_2h, home_territory_1h_2h, home_clean_breaks, home_defenders_beaten, home_offloads, home_rucks_won, home_mauls_won, home_turnovers_conceeded, away_possession_1h_2h, away_territory_1h_2h, away_clean_breaks, away_defenders_beaten, away_offloads, away_rucks_won, away_mauls_won, away_turnovers_conceeded, home_total_possession, home_total_territory, away_total_possesion, away_total_territory, home_scrum, home_lineout, away_scrum, away_lineout, home_tackles, home_tackle_perc, away_tackles, away_tackle_perc, home_red_cards, home_yellow_cards, home_free_kicks_con, away_red_cards, away_yellow_cards, away_free_kicks_con, home_penalties, away_penalties, date, competition, season, stadium, home_1h_poss, home_2h_poss, home_1h_terr, home_2h_terr, home_rucks_won_num, home_rucks_won_total_num, home_rucks_won_percent, home_mauls_won_num, home_mauls_won_total_num, home_mauls_won_percent, home_scrum_num, home_scrum_total_num, home_scrum_won_percent, home_lineout_num, home_lineout_total_num, home_lineout_won_percent, away_1h_poss, away_2h_poss, away_1h_terr, away_2h_terr, away_rucks_won_num, away_rucks_won_total_num, away_rucks_won_percent, away_mauls_won_num, away_mauls_won_total_num, away_mauls_won_percent, away_scrum_num, away_scrum_total_num, away_scrum_won_percent, away_lineout_num, away_lineout_total_num, away_lineout_won_percent, date_formatted, league_season]
Index: []

[0 rows x 96 columns]

In [5]:
error_games

[356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 432,
 434,
 435,
 436,
 437,
 440,
 441,
 442,
 443,
 444,
 445,
 447,
 448,
 450,
 451,
 452,
 453,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495]

In [14]:
all_df[all_df['game_id'] == all_df['game_id'].iloc[0]].drop_duplicates()

,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score
0,597160,271937,82,Sale Sharks,Robert du Preez,Conversion,37.0,27.0
1,597160,271937,81,Sale Sharks,Tom Curtis,Try,37.0,25.0
2,597160,271937,80,Leinster,Charlie Ngatai,Sub_Out,37.0,20.0
3,597160,271937,80,Sale Sharks,Robert du Preez,Conversion,37.0,20.0
4,597160,271937,79,Sale Sharks,Tommy Taylor,Try,37.0,18.0
5,597160,271937,78,Leinster,Hugo Keenan,Yellow_Card,37.0,13.0
6,597160,271937,71,Leinster,Sam Prendergast,Conversion,37.0,13.0
7,597160,271937,70,Leinster,Cian Healy,Try,35.0,13.0
8,597160,271937,70,Leinster,Ben Murphy,Sub_In,30.0,13.0
9,597160,271937,70,Leinster,Jamison Gibson-Park,Sub_Out,30.0,13.0
10,597160,271937,67,Sale Sharks,Nye Thomas,Sub_In,30.0,13.0
11,597160,271937,67,Sale Sharks,Raffi Quirke,Sub_Out,30.0,13.0
12,597160,271937,67,Sale Sharks,Ethan Caine,Sub_In,30.0,13.0
13,597160,271937,67,Sale Sharks,Ernst van Rhyn,Sub_Out,30.0,13.0
14,597160,271937,67,Sale Sharks,Ernst van Rhyn,Sub_In,30.0,13.0
15,597160,271937,67,Sale Sharks,Josh Beaumont,Sub_Out,30.0,13.0
16,597160,271937,66,Leinster,Sam Prendergast,Sub_In,30.0,13.0
17,597160,271937,66,Leinster,Ciaran Frawley,Sub_Out,30.0,13.0
18,597160,271937,66,Leinster,Jack Conan,Sub_In,30.0,13.0
19,597160,271937,66,Leinster,Caelan Doris,Sub_Out,30.0,13.0
20,597160,271937,64,Leinster,Cian Healy,Sub_In,30.0,13.0
21,597160,271937,64,Leinster,Andrew Porter,Sub_Out,30.0,13.0
22,597160,271937,64,Leinster,Ciaran Frawley,Conversion,30.0,13.0
23,597160,271937,62,Leinster,Ryan Baird,Try,28.0,13.0
24,597160,271937,60,Sale Sharks,Tom Curtis,Sub_In,23.0,13.0
25,597160,271937,60,Sale Sharks,Connor Doherty,Sub_Out,23.0,13.0
26,597160,271937,60,Leinster,Ronan Kelleher,Sub_In,23.0,13.0
27,597160,271937,60,Leinster,Dan Sheehan,Sub_Out,23.0,13.0
28,597160,271937,57,Sale Sharks,Josh Beaumont,Sub_In,23.0,13.0
29,597160,271937,57,Sale Sharks,Ernst van Rhyn,Sub_Out,23.0,13.0
30,597160,271937,57,Sale Sharks,Joe Carpenter,Sub_In,23.0,13.0
31,597160,271937,57,Sale Sharks,Telusa Veainu,Sub_Out,23.0,13.0
32,597160,271937,57,Sale Sharks,Tumy Onasanya,Sub_In,23.0,13.0
33,597160,271937,57,Sale Sharks,Ross Harrison,Sub_Out,23.0,13.0
34,597160,271937,57,Leinster,Ciaran Frawley,Conversion,23.0,13.0
35,597160,271937,57,Leinster,Robbie Henshaw,Try,21.0,13.0
36,597160,271937,56,Leinster,Charlie Ngatai,Sub_In,16.0,13.0
37,597160,271937,56,Leinster,Jordan Larmour,Sub_Out,16.0,13.0
38,597160,271937,52,Sale Sharks,Jonny Hill,Sub_In,16.0,13.0
39,597160,271937,52,Sale Sharks,Josh Beaumont,Sub_Out,16.0,13.0
40,597160,271937,48,Sale Sharks,Jean-Luc du Preez,Sub_In,16.0,13.0
41,597160,271937,48,Sale Sharks,Rouban Birch,Sub_Out,16.0,13.0
42,597160,271937,46,Sale Sharks,Asher Opoku-Fordjour,Sub_In,16.0,13.0
43,597160,271937,46,Sale Sharks,James Harper,Sub_Out,16.0,13.0
44,597160,271937,45,Leinster,Michael Ala'alatoa,Sub_In,16.0,13.0
45,597160,271937,45,Leinster,Thomas Clarkson,Sub_Out,16.0,13.0
46,597160,271937,43,Leinster,Jamison Gibson-Park,Try,16.0,13.0
47,597160,271937,40,Leinster,Joe McCarthy,Sub_In,11.0,13.0
48,597160,271937,40,Leinster,Jason Jenkins,Sub_Out,11.0,13.0
49,597160,271937,40,Leinster,Josh van der Flier,Try,11.0,13.0
50,597160,271937,37,Sale Sharks,James Harper,Yellow_Card,6.0,13.0
51,597160,271937,31,Leinster,Ciaran Frawley,Penalty_Goal,6.0,13.0
52,597160,271937,27,Sale Sharks,Robert du Preez,Conversion,3.0,13.0
53,597160,271937,25,Sale Sharks,Connor Doherty,Try,3.0,11.0
54,597160,271937,18,Sale Sharks,Robert du Preez,Penalty_Goal,3.0,6.0
55,597160,271937,15,Leinster,Ciaran Frawley,Penalty_Goal,3.0,3.0
56,597160,271937,4,Sale Sharks,Robert du Preez,Penalty_Goal,0.0,3.0
57,597160,271937,3,Leinster,Robbie Henshaw,Yellow_Card,NaN,NaN

In [ ]:
output_df = all_df[~all_df['Team'].str.contains(' half')].drop_.reset_index()
output_df

,index,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score
0,0,597814,270559,82,Stade Toulousain,Clement Verge,Try,22.0,8.0
1,1,597814,270559,76,Stade Toulousain,Juan Cruz Mallia,Yellow_Card,22.0,3.0
2,2,597814,270559,70,La Rochelle,Judicael Cancoriet,Sub_In,22.0,3.0
3,3,597814,270559,70,La Rochelle,Levani Botia,Sub_Out,22.0,3.0
4,4,597814,270559,59,La Rochelle,Ultan Dillane,Sub_In,22.0,3.0
...,...,...,...,...,...,...,...,...,...
95524,44,268769,270559,23,Agen,Alexi Bales,Try,3.0,11.0
95525,45,268769,270559,20,Agen,Burton Francis,Penalty_Goal,3.0,6.0
95526,46,268769,270559,20,Oyonnax,Jody Jenneker,Yellow_Card,3.0,3.0
95527,47,268769,270559,16,Agen,Burton Francis,Penalty_Goal,3.0,3.0
95528,48,268769,270559,14,Oyonnax,Nicky Robinson,Penalty_Goal,3.0,0.0

In [6]:
all_df.drop_duplicates().to_csv('formed_data/match_comm_data/Prem_data_v2.csv', index=False)

In [20]:
pd.concat(base_dfs[:3], axis=0)

,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score
0,167053,270557,80,7-0 End of second half,None,None,17.0,0.0
1,167053,270557,78,Leinster,John Cooney,Sub_In,17.0,0.0
2,167053,270557,78,Leinster,Ian Madigan,Sub_Out,17.0,0.0
3,167053,270557,75,Leinster,Brendan Macken,Sub_Out,17.0,0.0
4,167053,270557,75,Leinster,Ian Madigan,Conversion,17.0,0.0
...,...,...,...,...,...,...,...,...
44,167039,270557,32,Zebre,Quintin Geldenhuys,Yellow_Card,10.0,0.0
45,167039,270557,28,Leinster,Johnny Sexton,Conversion,10.0,0.0
46,167039,270557,26,Leinster,Andrew Conway,Try,8.0,0.0
47,167039,270557,25,Leinster,Johnny Sexton,Penalty_Goal,3.0,0.0
48,167039,270557,1,-0 Start of first half,None,None,NaN,NaN

In [14]:
base_dfs[-3]

,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score
0,290555,270557,81,-19 End of second half,None,None,3.0,19.0
1,290555,270557,78,Benetton Treviso,Federico Zani,Sub_Out,3.0,19.0
2,290555,270557,78,Benetton Treviso,Alberto Porolli,Sub_In,3.0,19.0
3,290555,270557,76,Benetton Treviso,Francesco Minto,Sub_Out,3.0,19.0
4,290555,270557,76,Benetton Treviso,Simone Ferrari,Sub_In,3.0,19.0
5,290555,270557,76,Benetton Treviso,David Odiete,Sub_Out,3.0,19.0
6,290555,270557,76,Benetton Treviso,Tommaso Allan,Sub_In,3.0,19.0
7,290555,270557,75,Zebre,Dries van Schalkwyk,Sub_Out,3.0,19.0
8,290555,270557,75,Zebre,Kayle van Zyl,Sub_In,3.0,19.0
9,290555,270557,75,Benetton Treviso,Tiziano Pasquali,Yellow_Card,3.0,19.0
10,290555,270557,73,Benetton Treviso,Tiziano Pasquali,Sub_In,3.0,19.0
11,290555,270557,73,Benetton Treviso,Simone Ferrari,Sub_Out,3.0,19.0
12,290555,270557,68,Benetton Treviso,Marco Fuser,Sub_Out,3.0,19.0
13,290555,270557,68,Benetton Treviso,Filo Paulo,Sub_In,3.0,19.0
14,290555,270557,67,Zebre,Guillermo Roan,Sub_In,3.0,19.0
15,290555,270557,67,Zebre,Pietro Ceccarelli,Sub_Out,3.0,19.0
16,290555,270557,67,Zebre,Andrea Lovotti,Sub_Out,3.0,19.0
17,290555,270557,67,Zebre,Andrea de Marchi,Sub_In,3.0,19.0
18,290555,270557,67,Zebre,Federico Ruzza,Sub_In,3.0,19.0
19,290555,270557,67,Zebre,Kayle van Zyl,Sub_Out,3.0,19.0
20,290555,270557,64,Benetton Treviso,Tito Tebaldi,Sub_Out,3.0,19.0
21,290555,270557,64,Benetton Treviso,Edoardo Gori,Sub_In,3.0,19.0
22,290555,270557,64,Benetton Treviso,Davide Giazzon,Sub_In,3.0,19.0
23,290555,270557,64,Benetton Treviso,Luca Bigi,Sub_Out,3.0,19.0
24,290555,270557,62,Zebre,Carlo Canna,Sub_Out,3.0,19.0
25,290555,270557,62,Zebre,Mattia Bellini,Sub_In,3.0,19.0
26,290555,270557,58,Benetton Treviso,Tommaso Iannone,Sub_Out,3.0,19.0
27,290555,270557,58,Benetton Treviso,Luca Sperandio,Sub_In,3.0,19.0
28,290555,270557,54,Benetton Treviso,Ian McKinley,Penalty_Goal,3.0,19.0
29,290555,270557,53,Zebre,Tommaso Castello,Sub_Out,3.0,16.0
30,290555,270557,53,Zebre,Tommaso Boni,Sub_In,3.0,16.0
31,290555,270557,50,Benetton Treviso,Ian McKinley,Penalty_Goal,3.0,16.0
32,290555,270557,43,Benetton Treviso,Ian McKinley,Penalty_Goal,3.0,13.0
33,290555,270557,41,Benetton Treviso,Robert Barbieri,Sub_Out,3.0,10.0
34,290555,270557,41,Benetton Treviso,Marco Lazzaroni,Sub_In,3.0,10.0
35,290555,270557,41,Zebre,Marcello Violi,Sub_Out,3.0,10.0
36,290555,270557,41,Zebre,Guglielmo Palazzani,Sub_In,3.0,10.0
37,290555,270557,41,Zebre,Jacopo Sarto,Sub_Out,3.0,10.0
38,290555,270557,41,Zebre,Johan Meyer,Sub_In,3.0,10.0
39,290555,270557,41,Zebre,Oliviero Fabiani,Sub_In,3.0,10.0
40,290555,270557,41,Zebre,Tommaso d'Apice,Sub_Out,3.0,10.0
41,290555,270557,40,-10 Start of second half,None,None,3.0,10.0
42,290555,270557,42,-10 End of first half,None,None,3.0,10.0
43,290555,270557,39,Benetton Treviso,Marco Fuser,Yellow_Card,3.0,10.0
44,290555,270557,35,Benetton Treviso,Ian McKinley,Penalty_Goal,3.0,10.0
45,290555,270557,17,Zebre,Carlo Canna,Penalty_Goal,3.0,7.0
46,290555,270557,11,Benetton Treviso,Ian McKinley,Conversion,0.0,7.0
47,290555,270557,10,Benetton Treviso,Marco Fuser,Try,0.0,5.0
48,290555,270557,1,-0 Start of first half,None,None,NaN,NaN

In [13]:
base_dfs[-2]

,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score
0,290496,270557,81,6-8 End of second half,None,None,26.0,8.0
1,290496,270557,75,Benetton Treviso,Tommaso Iannone,Sub_In,26.0,8.0
2,290496,270557,75,Benetton Treviso,Braam Steyn,Sub_Out,26.0,8.0
3,290496,270557,69,Dragons,Dorian Jones,Conversion,26.0,8.0
4,290496,270557,69,Dragons,Lewis Evans,Try,24.0,8.0
5,290496,270557,64,Dragons,Brok Harris,Sub_Out,19.0,8.0
6,290496,270557,64,Dragons,Lloyd Fairbrother,Sub_In,19.0,8.0
7,290496,270557,63,Dragons,Elliot Dee,Sub_Out,19.0,8.0
8,290496,270557,63,Dragons,Rhys Buckley,Sub_In,19.0,8.0
9,290496,270557,63,Dragons,Angus O'Brien,Sub_Out,19.0,8.0
10,290496,270557,63,Dragons,Dorian Jones,Sub_In,19.0,8.0
11,290496,270557,61,Benetton Treviso,Ian McKinley,Sub_In,19.0,8.0
12,290496,270557,61,Benetton Treviso,Tommaso Allan,Sub_Out,19.0,8.0
13,290496,270557,61,Benetton Treviso,Robert Barbieri,Sub_Out,19.0,8.0
14,290496,270557,61,Benetton Treviso,Marco Lazzaroni,Sub_In,19.0,8.0
15,290496,270557,60,Dragons,Ollie Griffiths,Sub_Out,19.0,8.0
16,290496,270557,60,Dragons,Nic Cudd,Sub_In,19.0,8.0
17,290496,270557,55,Dragons,Angus O'Brien,Penalty_Goal,19.0,8.0
18,290496,270557,51,Benetton Treviso,Alberto de Marchi,Sub_Out,13.0,8.0
19,290496,270557,51,Benetton Treviso,Federico Zani,Sub_In,13.0,8.0
20,290496,270557,51,Dragons,None,None,13.0,8.0
21,290496,270557,50,Dragons,Phil Price,Sub_Out,13.0,8.0
22,290496,270557,50,Dragons,Sam Hobbs,Sub_In,13.0,8.0
23,290496,270557,50,Dragons,Nick Crosswell,Sub_Out,13.0,8.0
24,290496,270557,50,Dragons,Rynard Landman,Sub_In,13.0,8.0
25,290496,270557,50,Benetton Treviso,Tito Tebaldi,Sub_Out,13.0,8.0
26,290496,270557,50,Benetton Treviso,Giorgio Bronzini,Sub_In,13.0,8.0
27,290496,270557,49,Benetton Treviso,Tiziano Pasquali,Sub_In,13.0,8.0
28,290496,270557,49,Benetton Treviso,Matteo Zanusso,Sub_Out,13.0,8.0
29,290496,270557,49,Benetton Treviso,Ornel Gega,Sub_In,13.0,8.0
30,290496,270557,49,Benetton Treviso,Davide Giazzon,Sub_Out,13.0,8.0
31,290496,270557,44,Dragons,Jack Dixon,Sub_In,13.0,8.0
32,290496,270557,44,Dragons,Pat Howard,Sub_Out,13.0,8.0
33,290496,270557,41,Benetton Treviso,Filo Paulo,Sub_In,13.0,8.0
34,290496,270557,41,Benetton Treviso,Marco Fuser,Sub_Out,13.0,8.0
35,290496,270557,40,3-8 Start of second half,None,None,13.0,8.0
36,290496,270557,44,3-8 End of first half,None,None,13.0,8.0
37,290496,270557,44,Dragons,Angus O'Brien,Penalty_Goal,13.0,8.0
38,290496,270557,36,Dragons,Sarel Pretorius,Yellow_Card,10.0,8.0
39,290496,270557,28,Dragons,Angus O'Brien,Conversion,10.0,8.0
40,290496,270557,27,Dragons,Sarel Pretorius,Try,8.0,8.0
41,290496,270557,24,Benetton Treviso,Tommaso Allan,Penalty_Goal,3.0,8.0
42,290496,270557,8,Benetton Treviso,Tito Tebaldi,Try,3.0,5.0
43,290496,270557,6,Dragons,Angus O'Brien,Penalty_Goal,3.0,0.0
44,290496,270557,1,-0 Start of first half,None,None,NaN,NaN

In [12]:
base_dfs[-1]

,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score
0,290537,270557,81,9-14 End of second half,None,None,29.0,14.0
1,290537,270557,78,Dragons,Adam Warren,Sub_In,29.0,14.0
2,290537,270557,78,Dragons,Tyler Morgan,Sub_Out,29.0,14.0
3,290537,270557,78,Dragons,Darran Harris,Sub_In,29.0,14.0
4,290537,270557,78,Dragons,Rhys Buckley,Sub_Out,29.0,14.0
5,290537,270557,69,Zebre,Serafin Bordoli,Yellow_Card,29.0,14.0
6,290537,270557,69,Zebre,Guglielmo Palazzani,Sub_In,29.0,14.0
7,290537,270557,69,Zebre,Kayle van Zyl,Sub_Out,29.0,14.0
8,290537,270557,67,Dragons,Tom Prydie,Sub_In,29.0,14.0
9,290537,270557,67,Dragons,Pat Howard,Sub_Out,29.0,14.0
10,290537,270557,65,Zebre,Carlo Canna,Sub_Out,29.0,14.0
11,290537,270557,65,Zebre,Serafin Bordoli,Sub_In,29.0,14.0
12,290537,270557,65,Zebre,Joshua Furno,Sub_In,29.0,14.0
13,290537,270557,65,Zebre,Gideon Koegelenberg,Sub_Out,29.0,14.0
14,290537,270557,62,Dragons,Angus O'Brien,Sub_Out,29.0,14.0
15,290537,270557,62,Dragons,Dorian Jones,Sub_In,29.0,14.0
16,290537,270557,59,Zebre,Bruno Postiglioni,Sub_In,29.0,14.0
17,290537,270557,59,Zebre,Andrea Lovotti,Sub_Out,29.0,14.0
18,290537,270557,59,Zebre,Tommaso Castello,Sub_In,29.0,14.0
19,290537,270557,59,Zebre,Lloyd Greef,Sub_Out,29.0,14.0
20,290537,270557,58,Dragons,Harrison Keddie,Sub_In,29.0,14.0
21,290537,270557,58,Dragons,Nick Crosswell,Sub_Out,29.0,14.0
22,290537,270557,55,Zebre,Maxime Mbanda,Sub_In,29.0,14.0
23,290537,270557,55,Zebre,Johan Meyer,Sub_Out,29.0,14.0
24,290537,270557,53,Zebre,Carlo Canna,Conversion,29.0,14.0
25,290537,270557,52,Zebre,Johan Meyer,Try,27.0,14.0
26,290537,270557,51,Zebre,Carlo Canna,Conversion,22.0,14.0
27,290537,270557,50,Zebre,Edoardo Padovani,Try,20.0,14.0
28,290537,270557,47,Zebre,Pietro Ceccarelli,Sub_In,15.0,14.0
29,290537,270557,47,Zebre,Dario Chistolini,Sub_Out,15.0,14.0
30,290537,270557,47,Zebre,Tommaso d'Apice,Sub_Out,15.0,14.0
31,290537,270557,47,Zebre,Oliviero Fabiani,Sub_In,15.0,14.0
32,290537,270557,46,Dragons,Ollie Griffiths,Sub_Out,15.0,14.0
33,290537,270557,46,Dragons,Nic Cudd,Sub_In,15.0,14.0
34,290537,270557,46,Dragons,Angus O'Brien,Conversion,15.0,14.0
35,290537,270557,45,Dragons,Adam Hughes,Try,15.0,12.0
36,290537,270557,40,5-7 Start of second half,None,None,15.0,7.0
37,290537,270557,41,5-7 End of first half,None,None,15.0,7.0
38,290537,270557,39,Dragons,Lloyd Fairbrother,Sub_In,15.0,7.0
39,290537,270557,39,Dragons,Brok Harris,Sub_Out,15.0,7.0
40,290537,270557,39,Dragons,Sam Hobbs,Sub_In,15.0,7.0
41,290537,270557,39,Dragons,Phil Price,Sub_Out,15.0,7.0
42,290537,270557,31,Zebre,Carlo Canna,Conversion,15.0,7.0
43,290537,270557,30,Zebre,Derick Minnie,Try,13.0,7.0
44,290537,270557,14,Zebre,Federico Ruzza,Try,8.0,7.0
45,290537,270557,8,Dragons,Angus O'Brien,Conversion,3.0,7.0
46,290537,270557,7,Dragons,Cory Hill,Try,3.0,5.0
47,290537,270557,5,Zebre,Carlo Canna,Penalty_Goal,3.0,0.0
48,290537,270557,1,-0 Start of first half,None,None,NaN,NaN

In [10]:
all_df

,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score,game_id,league_id,...,Home_Score,Away_Score,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score
0,167053.0,270557.0,80.0,7-0 End of second half,None,None,17.0,0.0,167046.0,270557.0,...,26.0,8.0,290537.0,270557.0,81.0,9-14 End of second half,None,None,29.0,14.0
1,167053.0,270557.0,78.0,Leinster,John Cooney,Sub_In,17.0,0.0,167046.0,270557.0,...,26.0,8.0,290537.0,270557.0,78.0,Dragons,Adam Warren,Sub_In,29.0,14.0
2,167053.0,270557.0,78.0,Leinster,Ian Madigan,Sub_Out,17.0,0.0,167046.0,270557.0,...,26.0,8.0,290537.0,270557.0,78.0,Dragons,Tyler Morgan,Sub_Out,29.0,14.0
3,167053.0,270557.0,75.0,Leinster,Brendan Macken,Sub_Out,17.0,0.0,167046.0,270557.0,...,26.0,8.0,290537.0,270557.0,78.0,Dragons,Darran Harris,Sub_In,29.0,14.0
4,167053.0,270557.0,75.0,Leinster,Ian Madigan,Conversion,17.0,0.0,167046.0,270557.0,...,24.0,8.0,290537.0,270557.0,78.0,Dragons,Rhys Buckley,Sub_Out,29.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
test_df = grab_match_comms_cards(game=598075, league=270557)

In [117]:
test_df

,game_id,league_id,Time,Team,Player,Event_Type,Home_Score,Away_Score
0,598075,270557,75,Glasgow Warriors,George Horne,Penalty_Goal,10.0,17.0
1,598075,270557,74,Munster,Alex Nankivell,Red_Card,10.0,14.0
2,598075,270557,73,Munster,Alex Kendellen,Sub_In,10.0,14.0
3,598075,270557,73,Munster,John Hodnett,Sub_Out,10.0,14.0
4,598075,270557,71,Glasgow Warriors,Matt Fagerson,Sub_In,10.0,14.0
5,598075,270557,71,Glasgow Warriors,Euan Ferrie,Sub_Out,10.0,14.0
6,598075,270557,71,Glasgow Warriors,Oli Kebble,Sub_In,10.0,14.0
7,598075,270557,71,Glasgow Warriors,Jamie Bhatti,Sub_Out,10.0,14.0
8,598075,270557,66,Munster,John Ryan,Sub_In,10.0,14.0
9,598075,270557,66,Munster,Jeremy Loughman,Sub_Out,10.0,14.0
10,598075,270557,62,Munster,Sean O'Brien,Sub_In,10.0,14.0
11,598075,270557,62,Munster,Simon Zebo,Sub_Out,10.0,14.0
12,598075,270557,61,Glasgow Warriors,Euan Ferrie,Sub_In,10.0,14.0
13,598075,270557,61,Glasgow Warriors,Matt Fagerson,Sub_Out,10.0,14.0
14,598075,270557,58,Munster,Alex Nankivell,Sub_In,10.0,14.0
15,598075,270557,58,Munster,Sean O'Brien,Sub_Out,10.0,14.0
16,598075,270557,58,Glasgow Warriors,Henco Venter,Sub_In,10.0,14.0
17,598075,270557,58,Glasgow Warriors,Rory Darge,Sub_Out,10.0,14.0
18,598075,270557,58,Glasgow Warriors,Jamie Dobie,Sub_In,10.0,14.0
19,598075,270557,58,Glasgow Warriors,Sebastian Cancelliere,Sub_Out,10.0,14.0
20,598075,270557,58,Glasgow Warriors,George Turner,Sub_In,10.0,14.0
21,598075,270557,58,Glasgow Warriors,Johnny Matthews,Sub_Out,10.0,14.0
22,598075,270557,58,Glasgow Warriors,Max Williamson,Sub_In,10.0,14.0
23,598075,270557,58,Glasgow Warriors,Richie Gray,Sub_Out,10.0,14.0
24,598075,270557,58,Munster,Conor Murray,Sub_In,10.0,14.0
25,598075,270557,58,Munster,Craig Casey,Sub_Out,10.0,14.0
26,598075,270557,57,Munster,Jack Crowley,Conversion,10.0,14.0
27,598075,270557,56,Munster,Antoine Frisch,Try,8.0,14.0
28,598075,270557,55,Munster,Gavin Coombes,Sub_In,3.0,14.0
29,598075,270557,55,Munster,Jack O'Donoghue,Sub_Out,3.0,14.0
30,598075,270557,52,Glasgow Warriors,George Horne,Conversion,3.0,14.0
31,598075,270557,51,Glasgow Warriors,Sebastian Cancelliere,Try,3.0,12.0
32,598075,270557,47,Munster,Sean O'Brien,Sub_In,3.0,7.0
33,598075,270557,47,Munster,Alex Nankivell,Sub_Out,3.0,7.0
34,598075,270557,46,Munster,RG Snyman,Sub_In,3.0,7.0
35,598075,270557,46,Munster,Fineen Wycherley,Sub_Out,3.0,7.0
36,598075,270557,46,Munster,Oli Jager,Sub_In,3.0,7.0
37,598075,270557,46,Munster,Stephen Archer,Sub_Out,3.0,7.0
38,598075,270557,46,Munster,Diarmuid Barron,Sub_In,3.0,7.0
39,598075,270557,46,Munster,Niall Scannell,Sub_Out,3.0,7.0
40,598075,270557,40,Glasgow Warriors,Matt Fagerson,Yellow_Card,3.0,7.0
41,598075,270557,25,Glasgow Warriors,George Horne,Conversion,3.0,7.0
42,598075,270557,24,Glasgow Warriors,Kyle Steyn,Try,3.0,5.0
43,598075,270557,12,Munster,Jack Crowley,Penalty_Goal,3.0,0.0
44,598075,270557,11,Glasgow Warriors,Richie Gray,Yellow_Card,NaN,NaN

### Continuing to Other Maintenance Tasks

In [2]:
def assign_season(df):
    if df['month'] >= 9:
        league_season = str((df['season'])) + '-' + str(df['season'] + 1)
    elif df['league_id'] == 242041:
        league_season = df['season']
    else:
        league_season = str(df['season'] - 1) + '-' + str(df['season'])
    return league_season
    

def rejoin_date_df(sched_df, game_df,path):
    # sched_df[['month', 'day']] = sched_df['date'].apply(parse_game_date_v2).apply(pd.Series)
    # sched_df['date_formatted'] = sched_df.apply(lambda x: datetime.datetime(x['season'], x['month'], x['day']), axis=1)

    sched_df['date_formatted'] = sched_df.apply(parse_game_date_v3, axis=1)
    sched_df[['month', 'day']] = sched_df['date_formatted'].apply(lambda x: (x.month, x.day)).apply(pd.Series)
    sched_df['league_season'] = sched_df.apply(assign_season, axis=1)

    merged_df = game_df.merge(
        sched_df[['game_id', 'date_formatted', 'league_season']],
        how='left',
        on='game_id'
    )

    grouped_df = merged_df.groupby('league_season')
    season_dict = {name: group for name, group in grouped_df}

    for season, value in season_dict.items():
        value.to_csv(path+'_'+str(season)+'.csv', index=False)
        print("DF for season {} saved to {}".format(str(season), path+'_'+str(season)+'.csv'))


def run_joiner_output(sched_path, game_path, output_path):
    sched_concat_df = pd.concat(list(map(pd.read_csv, sched_path)))
    game_concat_df = pd.concat(list(map(pd.read_csv, game_path)))

    sched_concat_df.loc[sched_concat_df['date'] == 'Mar, Dic 26', 'date'] = 'Tue, Dec 26'

    rejoin_date_df(
        sched_df=sched_concat_df, 
        game_df=game_concat_df, 
        path=output_path
    )

In [8]:
sched_files_use_rchamp = [sched_path + '/' + f'RChamp_schedule_data_{i}.csv' for i in range(2011, 2024) if i != 2020]
game_files_use_rchamp = [game_path + '/' + f'RChamp_game_stats_{i}.csv' for i in range(2011, 2024) if i != 2020]

sched_files_use_prem = [sched_path + '/' + f'Prem_schedule_data_{i}.csv' for i in range(2013, 2019) if i != 2020]
game_files_use_prem = [game_path + '/' + f'Prem_game_stats_{i}.csv' for i in range(2013, 2019) if i != 2020]

In [12]:
sched_files_use_champ_cup = [sched_path + '/' + f'ChampCup_schedule_data_{i}.csv' for i in range(2011, 2024)]
game_files_use_champ_cup = [game_path + '/' + f'ChampCup_game_stats_{i}.csv' for i in range(2011, 2024)]

champ_cup_file_path = 'formed_data/game_data_v2/ChampCup_game_data_v2'
run_joiner_output(sched_files_use_champ_cup, game_files_use_champ_cup, champ_cup_file_path)

DF for season 2010-2011 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2010-2011.csv
DF for season 2011-2012 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2011-2012.csv
DF for season 2012-2013 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2012-2013.csv
DF for season 2013-2014 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2013-2014.csv
DF for season 2014-2015 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2014-2015.csv
DF for season 2015-2016 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2015-2016.csv
DF for season 2016-2017 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2016-2017.csv
DF for season 2017-2018 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2017-2018.csv
DF for season 2018-2019 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2018-2019.csv
DF for season 2019-2020 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2019-2020.csv
DF for season 2020-2021 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2020-2021.csv
DF for season 2021-2022 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2021-2022.csv
DF for season 2023-2024 saved to formed_data/game_data_v2/ChampCup_game_data_v2_2023-2024.csv

In [6]:
sched_files_use_urc = [sched_path + '/' + f'URC_schedule_data_{i}.csv' for i in range(2011, 2024)]
game_files_use_urc = [game_path + '/' + f'URC_game_stats_{i}.csv' for i in range(2011, 2024)]

urc_file_path = 'formed_data/game_data_v2/URC_game_data_v2'
run_joiner_output(sched_files_use_urc, game_files_use_urc, urc_file_path)

DF for season 2010-2011 saved to formed_data/game_data_v2/URC_game_data_v2_2010-2011.csv
DF for season 2011-2012 saved to formed_data/game_data_v2/URC_game_data_v2_2011-2012.csv
DF for season 2012-2013 saved to formed_data/game_data_v2/URC_game_data_v2_2012-2013.csv
DF for season 2013-2014 saved to formed_data/game_data_v2/URC_game_data_v2_2013-2014.csv
DF for season 2014-2015 saved to formed_data/game_data_v2/URC_game_data_v2_2014-2015.csv
DF for season 2015-2016 saved to formed_data/game_data_v2/URC_game_data_v2_2015-2016.csv
DF for season 2016-2017 saved to formed_data/game_data_v2/URC_game_data_v2_2016-2017.csv
DF for season 2017-2018 saved to formed_data/game_data_v2/URC_game_data_v2_2017-2018.csv
DF for season 2018-2019 saved to formed_data/game_data_v2/URC_game_data_v2_2018-2019.csv
DF for season 2019-2020 saved to formed_data/game_data_v2/URC_game_data_v2_2019-2020.csv
DF for season 2020-2021 saved to formed_data/game_data_v2/URC_game_data_v2_2020-2021.csv
DF for season 2021-2022 saved to formed_data/game_data_v2/URC_game_data_v2_2021-2022.csv
DF for season 2022-2023 saved to formed_data/game_data_v2/URC_game_data_v2_2022-2023.csv
DF for season 2023-2024 saved to formed_data/game_data_v2/URC_game_data_v2_2023-2024.csv

In [5]:
sched_files_use_prem = [sched_path + '/' + f'Prem_schedule_data_{i}.csv' for i in range(2011, 2024)]
game_files_use_prem = [game_path + '/' + f'Prem_game_stats_{i}.csv' for i in range(2011, 2024)]

prem_file_path = 'formed_data/game_data_v2/Prem_game_data_v2'
run_joiner_output(sched_files_use_prem, game_files_use_prem, prem_file_path)

DF for season 2010-2011 saved to formed_data/game_data_v2/Prem_game_data_v2_2010-2011.csv
DF for season 2011-2012 saved to formed_data/game_data_v2/Prem_game_data_v2_2011-2012.csv
DF for season 2012-2013 saved to formed_data/game_data_v2/Prem_game_data_v2_2012-2013.csv
DF for season 2013-2014 saved to formed_data/game_data_v2/Prem_game_data_v2_2013-2014.csv
DF for season 2014-2015 saved to formed_data/game_data_v2/Prem_game_data_v2_2014-2015.csv
DF for season 2015-2016 saved to formed_data/game_data_v2/Prem_game_data_v2_2015-2016.csv
DF for season 2016-2017 saved to formed_data/game_data_v2/Prem_game_data_v2_2016-2017.csv
DF for season 2017-2018 saved to formed_data/game_data_v2/Prem_game_data_v2_2017-2018.csv
DF for season 2018-2019 saved to formed_data/game_data_v2/Prem_game_data_v2_2018-2019.csv
DF for season 2019-2020 saved to formed_data/game_data_v2/Prem_game_data_v2_2019-2020.csv
DF for season 2020-2021 saved to formed_data/game_data_v2/Prem_game_data_v2_2020-2021.csv
DF for season 2021-2022 saved to formed_data/game_data_v2/Prem_game_data_v2_2021-2022.csv
DF for season 2022-2023 saved to formed_data/game_data_v2/Prem_game_data_v2_2022-2023.csv
DF for season 2023-2024 saved to formed_data/game_data_v2/Prem_game_data_v2_2023-2024.csv

In [7]:
sched_files_use_sr = [sched_path + '/' + f'SR_schedule_data_{i}.csv' for i in range(2011, 2021)]
game_files_use_sr = [game_path + '/' + f'SR_game_stats_{i}.csv' for i in range(2011, 2021)]

sr_file_path = 'formed_data/game_data_v2/SR_game_data_v2'
run_joiner_output(sched_files_use_sr, game_files_use_sr, sr_file_path)

DF for season 2011 saved to formed_data/game_data_v2/SR_game_data_v2_2011.csv
DF for season 2012 saved to formed_data/game_data_v2/SR_game_data_v2_2012.csv
DF for season 2013 saved to formed_data/game_data_v2/SR_game_data_v2_2013.csv
DF for season 2014 saved to formed_data/game_data_v2/SR_game_data_v2_2014.csv
DF for season 2015 saved to formed_data/game_data_v2/SR_game_data_v2_2015.csv
DF for season 2016 saved to formed_data/game_data_v2/SR_game_data_v2_2016.csv
DF for season 2017 saved to formed_data/game_data_v2/SR_game_data_v2_2017.csv
DF for season 2018 saved to formed_data/game_data_v2/SR_game_data_v2_2018.csv
DF for season 2019 saved to formed_data/game_data_v2/SR_game_data_v2_2019.csv
DF for season 2020 saved to formed_data/game_data_v2/SR_game_data_v2_2020.csv

In [6]:
sched_files_use_sr

['formed_data/game_schedule_data/SR_schedule_data_2011.csv',
 'formed_data/game_schedule_data/SR_schedule_data_2012.csv',
 'formed_data/game_schedule_data/SR_schedule_data_2013.csv',
 'formed_data/game_schedule_data/SR_schedule_data_2014.csv',
 'formed_data/game_schedule_data/SR_schedule_data_2015.csv',
 'formed_data/game_schedule_data/SR_schedule_data_2016.csv',
 'formed_data/game_schedule_data/SR_schedule_data_2017.csv',
 'formed_data/game_schedule_data/SR_schedule_data_2018.csv',
 'formed_data/game_schedule_data/SR_schedule_data_2019.csv',
 'formed_data/game_schedule_data/SR_schedule_data_2020.csv']

In [ ]:
six_nations_file_path = 'formed_data/game_data_v2/SixNat_game_data_v2'
rchamp_file_path = 'formed_data/game_data_v2/RChamp_game_data_v2'


run_joiner_output(six_nations_sched_files, six_nations_game_files, six_nations_file_path)
run_joiner_output(sched_files_use_rchamp, game_files_use_rchamp, rchamp_file_path)

DF for season 2010-2011 saved to formed_data/game_data_v2/SixNat_game_data_v2_2010-2011.csv
DF for season 2011-2012 saved to formed_data/game_data_v2/SixNat_game_data_v2_2011-2012.csv
DF for season 2012-2013 saved to formed_data/game_data_v2/SixNat_game_data_v2_2012-2013.csv
DF for season 2013-2014 saved to formed_data/game_data_v2/SixNat_game_data_v2_2013-2014.csv
DF for season 2014-2015 saved to formed_data/game_data_v2/SixNat_game_data_v2_2014-2015.csv
DF for season 2015-2016 saved to formed_data/game_data_v2/SixNat_game_data_v2_2015-2016.csv
DF for season 2016-2017 saved to formed_data/game_data_v2/SixNat_game_data_v2_2016-2017.csv
DF for season 2017-2018 saved to formed_data/game_data_v2/SixNat_game_data_v2_2017-2018.csv
DF for season 2018-2019 saved to formed_data/game_data_v2/SixNat_game_data_v2_2018-2019.csv
DF for season 2019-2020 saved to formed_data/game_data_v2/SixNat_game_data_v2_2019-2020.csv
DF for season 2020-2021 saved to formed_data/game_data_v2/SixNat_game_data_v2_2020-2021.csv
DF for season 2021-2022 saved to formed_data/game_data_v2/SixNat_game_data_v2_2021-2022.csv
DF for season 2022-2023 saved to formed_data/game_data_v2/SixNat_game_data_v2_2022-2023.csv
DF for season 2023-2024 saved to formed_data/game_data_v2/SixNat_game_data_v2_2023-2024.csv
DF for season 2010-2011 saved to formed_data/game_data_v2/RChamp_game_data_v2_2010-2011.csv
DF for season 2011-2012 saved to formed_data/game_data_v2/RChamp_game_data_v2_2011-2012.csv
DF for season 2012-2013 saved to formed_data/game_data_v2/RChamp_game_data_v2_2012-2013.csv
DF for season 2013-2014 saved to formed_data/game_data_v2/RChamp_game_data_v2_2013-2014.csv
DF for season 2014-2015 saved to formed_data/game_data_v2/RChamp_game_data_v2_2014-2015.csv
DF for season 2015-2016 saved to formed_data/game_data_v2/RChamp_game_data_v2_2015-2016.csv
DF for season 2016-2017 saved to formed_data/game_data_v2/RChamp_game_data_v2_2016-2017.csv
DF for season 2017-2018 saved to formed_data/game_data_v2/RChamp_game_data_v2_2017-2018.csv
DF for season 2018-2019 saved to formed_data/game_data_v2/RChamp_game_data_v2_2018-2019.csv
DF for season 2020-2021 saved to formed_data/game_data_v2/RChamp_game_data_v2_2020-2021.csv
DF for season 2021-2022 saved to formed_data/game_data_v2/RChamp_game_data_v2_2021-2022.csv
DF for season 2022-2023 saved to formed_data/game_data_v2/RChamp_game_data_v2_2022-2023.csv

In [ ]:
sched_concat_t14_df = pd.concat(list(map(pd.read_csv, sched_files_use_t14)))
game_concat_t14_df = pd.concat(list(map(pd.read_csv, game_files_use_t14)))

In [ ]:
sched_concat_t14_df = pd.concat(list(map(pd.read_csv, sched_files_use_s)))
game_concat_t14_df = pd.concat(list(map(pd.read_csv, game_files_use_t14)))

In [34]:
sched_files_use_urc = [sched_path + '/' + f'URC_schedule_data_{i}.csv' for i in range(2011, 2020)]
game_files_use_urc= [game_path + '/' + f'URC_game_stats_{i}.csv' for i in range(2011, 2020)]

sched_files_use_t14 = [sched_path + '/' + f'T14_schedule_data_{i}.csv' for i in range(2011, 2020) if i != 2013]
# sched_files_use_t14 = sched_files_use_t14.remove('formed_data/game_schedule_data/T14_schedule_data_2014.csv')
game_files_use_t14 = [game_path + '/' + f'T14_game_stats_{i}.csv' for i in range(2011, 2020) if i != 2013]
# game_files_use_t14 = game_files_use_t14.remove('formed_data/game_data/T14_game_stats_2014.csv')
sched_files_use_t14

['formed_data/game_schedule_data/T14_schedule_data_2011.csv',
 'formed_data/game_schedule_data/T14_schedule_data_2012.csv',
 'formed_data/game_schedule_data/T14_schedule_data_2014.csv',
 'formed_data/game_schedule_data/T14_schedule_data_2015.csv',
 'formed_data/game_schedule_data/T14_schedule_data_2016.csv',
 'formed_data/game_schedule_data/T14_schedule_data_2017.csv',
 'formed_data/game_schedule_data/T14_schedule_data_2018.csv',
 'formed_data/game_schedule_data/T14_schedule_data_2019.csv']

In [9]:
sched_concat_t14_df = pd.concat(list(map(pd.read_csv, sched_files_use_t14)))
game_concat_t14_df = pd.concat(list(map(pd.read_csv, game_files_use_t14)))

In [29]:
sched_concat_df = pd.concat(list(map(pd.read_csv, sched_files_use_urc)))
game_concat_df = pd.concat(list(map(pd.read_csv, game_files_use_urc)))

In [10]:
sched_concat_t14_df['date']

0      Fri, Dec 30
1      Fri, Dec 23
2       Sat, Dec 3
3      Sat, Nov 26
4       Sat, Nov 5
          ...
183     Sat, Oct 5
184    Sat, Aug 31
185     Sat, May 4
186    Sat, Feb 23
187    Sat, Mar 23
Name: date, Length: 1477, dtype: object

In [11]:
sched_concat_df['date']

0     Fri, Dec 30
1     Mon, Dec 26
2      Sat, Dec 3
3     Sat, Nov 26
4      Fri, Nov 4
         ...
95    Sat, Sep 28
96    Sat, Apr 27
97    Sat, Apr 13
98    Sat, Feb 23
99    Sat, Feb 16
Name: date, Length: 1197, dtype: object

In [13]:
dateparser.parse(sched_concat_t14_df['date'].iloc[0], languages=['en'])

datetime.datetime(2025, 12, 30, 0, 0)

In [24]:
dateparser.parse('Mar, Dic 26', languages=['es'])

In [22]:
sched_concat_df['date'].iloc[65]

'Fri, Jan 7'

In [31]:
sched_concat_df.loc[sched_concat_df['date'] == 'Mar, Dic 26', 'date'] = 'Tue, Dec 26'

In [15]:
for i in range(len(sched_concat_df)):
    if dateparser.parse(sched_concat_df['date'].iloc[0], languages=['en']) == None:
        print(i)

In [12]:
sched_concat_t14_df['date_formatted'] = sched_concat_t14_df.apply(parse_game_date_v3, axis=1)

In [19]:
sched_concat_df[sched_concat_df['date'] == 'Mar, Dic 26']

,date,home_team,away_team,home_team_abbr,away_team_abbr,game_link,score,home_score,away_score,competition,stadium,game_id,league_id,season
65,"Mar, Dic 26",Scarlets,Ospreys,SCA,OSP,/rugby/match/_/gameId/291940/league/270557,12 - 9,12,9,United Rugby Championship,"Parc y Scarlets, Llanelli",291940.0,270557.0,2017

In [26]:
sched_concat_df['date_formatted'] = sched_concat_df.apply(parse_game_date_v3, axis=1)
sched_concat_df['date_formatted']

Fri, Dec 30
Mon, Dec 26
Sat, Dec 3
Sat, Nov 26
Fri, Nov 4
Fri, Oct 28
Sat, Oct 8
Fri, Sep 30
Fri, Sep 23
Sat, Sep 17
Fri, Sep 9
Sat, Sep 3
Sat, May 28
Sat, May 14
Fri, May 6
Sat, Apr 23
Sat, Apr 16
Sat, Apr 2
Fri, Mar 25
Sat, Mar 5
Sun, Feb 27
Fri, Feb 18
Sun, Feb 13
Sat, Jan 8
Sat, Jan 1
Mon, Dec 26
Fri, Dec 2
Sat, Nov 26
Fri, Oct 28
Sat, Oct 8
Sat, Oct 1
Sat, Sep 24
Sat, Sep 17
Fri, Sep 9
Fri, Sep 2
Fri, May 13
Fri, May 6
Sat, Apr 23
Sat, Apr 16
Sun, Mar 27
Fri, Mar 4
Fri, Feb 25
Sat, Feb 19
Thu, Feb 10
Fri, Jan 7
Sat, Jan 1
Fri, Dec 2
Fri, Nov 25
Sat, Nov 5
Sat, Oct 29
Fri, Oct 7
Fri, Sep 30
Sun, Sep 25
Fri, Sep 16
Sat, Sep 10
Fri, Sep 2
Fri, May 6
Fri, Apr 22
Fri, Apr 1
Fri, Mar 25
Fri, Mar 18
Fri, Mar 4
Fri, Feb 25
Fri, Feb 18
Sun, Feb 13
Fri, Jan 7
Mon, Dec 26
Sat, Nov 26
Sat, Nov 5
Fri, Oct 28
Fri, Sep 30
Sat, Sep 17
Sat, Sep 10
Fri, May 6
Fri, Apr 15
Sat, Apr 2
Sat, Mar 26
Sat, Mar 5
Sun, Feb 27
Sat, Feb 19
Fri, Dec 30
Fri, Nov 25
Fri, Oct 7
Sat, Oct 1
Sat, Sep 10
Sun, Sep 4
Fri, May 6
Fri, Apr 22
Sun, Mar 27
Thu, Feb 24
Sat, Feb 12
Sat, Jan 8
Sat, Jan 1
Fri, Dec 23
Thu, Nov 24
Sat, Oct 29
Sat, Oct 8
Sat, Oct 1
Sun, Sep 11
Fri, Sep 2
Fri, Apr 29
Thu, Apr 21
Fri, Apr 15
Fri, Mar 4
Fri, Feb 11
Fri, Jan 7
Sun, Dec 4
Sat, Oct 29
Fri, Oct 7
Fri, Sep 23
Sat, Sep 17
Fri, Apr 22
Sun, Apr 3
Fri, Feb 25
Sun, Feb 20
Sat, Feb 12
Thu, Jan 6
Mon, Dec 26
Fri, Dec 2
Sat, Nov 5
Sat, Sep 24
Fri, Sep 16
Fri, May 6
Fri, Apr 15
Fri, Apr 1
Sun, Jan 2
Fri, Dec 2
Sat, Sep 3
Sat, Mar 26
Fri, Mar 11
Fri, Mar 4
Fri, Feb 18
Sat, Dec 31
Fri, Dec 23
Fri, Sep 23
Sat, Apr 16
Fri, Mar 18
Sat, Nov 5
Sat, Apr 2
Sat, Dec 29
Fri, Dec 21
Sat, Dec 1
Fri, Nov 23
Sun, Nov 4
Sat, Oct 27
Sat, Oct 6
Fri, Sep 28
Sat, Sep 22
Sat, Sep 15
Sat, Sep 8
Sat, Sep 1
Sun, May 27
Sat, May 12
Sat, May 5
Fri, Apr 20
Fri, Apr 13
Sat, Mar 31
Fri, Mar 23
Fri, Mar 2
Sat, Feb 25
Fri, Feb 17
Thu, Feb 9
Sat, Jan 7
Sun, Jan 1
Mon, Dec 31
Wed, Dec 26
Fri, Nov 30
Fri, Nov 23
Sat, Oct 27
Fri, Oct 5
Sat, Sep 29
Fri, Sep 21
Fri, Sep 14
Sat, Sep 8
Fri, Aug 31
Fri, May 11
Sat, May 5
Fri, Apr 20
Sat, Apr 14
Sat, Mar 31
Fri, Mar 2
Fri, Feb 24
Fri, Feb 17
Fri, Feb 10
Fri, Jan 6
Sun, Jan 1
Sat, Dec 29
Sat, Dec 22
Sat, Dec 1
Sun, Nov 25
Fri, Nov 2
Fri, Oct 26
Sat, Sep 22
Fri, Sep 14
Fri, Sep 7
Sat, Sep 1
Sat, May 5
Sat, Apr 21
Sat, Apr 14
Sat, Mar 24
Sun, Mar 11
Sat, Mar 3
Fri, Feb 24
Sat, Feb 18
Sat, Jan 7
Sat, Dec 29
Fri, Dec 21
Fri, Nov 2
Sat, Oct 27
Sat, Oct 6
Fri, Sep 28
Fri, Sep 21
Fri, Sep 7
Fri, Aug 31
Sat, May 5
Sun, Apr 22
Fri, Mar 30
Fri, Mar 23
Sat, Feb 18
Thu, Feb 9
Sat, Jan 7
Sun, Jan 1
Fri, Dec 21
Sun, Dec 2
Sat, Nov 3
Fri, Oct 26
Fri, Oct 5
Sat, Sep 29
Sat, Sep 15
Sat, May 5
Sun, Apr 15
Fri, Mar 30
Sat, Mar 24
Fri, Mar 2
Thu, Feb 23
Fri, Nov 23
Sun, Nov 18
Fri, Nov 2
Fri, Oct 26
Fri, Oct 5
Fri, Sep 28
Sat, Apr 14
Fri, Mar 30
Sat, Mar 24
Fri, Mar 2
Fri, Feb 17
Fri, Feb 10
Fri, Jan 6
Wed, Dec 26
Sun, Nov 25
Sat, Sep 22
Sat, Sep 15
Fri, Sep 7
Sat, Sep 1
Sun, Apr 22
Thu, Mar 15
Sat, Mar 3
Fri, Feb 10
Sat, Dec 1
Fri, Nov 23
Sat, Nov 3
Fri, Sep 7
Sat, Apr 21
Fri, Mar 30
Fri, Feb 24
Sat, Jan 7
Sat, Dec 1
Fri, Sep 28
Fri, Aug 31
Fri, Apr 13
Fri, Mar 23
Sun, Feb 26
Sat, Feb 18
Sat, Dec 29
Sat, Dec 22
Fri, Oct 5
Sat, May 5
Fri, Sep 14
Sat, Dec 28
Fri, Dec 20
Sat, Nov 30
Fri, Nov 22
Sat, Nov 2
Fri, Oct 25
Fri, Oct 4
Fri, Sep 27
Sat, Sep 21
Fri, Sep 13
Fri, Sep 6
Sat, May 25
Fri, May 10
Fri, May 3
Fri, Apr 19
Fri, Apr 12
Sat, Mar 30
Fri, Mar 22
Fri, Mar 1
Fri, Feb 22
Fri, Feb 15
Fri, Feb 8
Fri, Jan 4
Fri, Dec 20
Sat, Nov 30
Sun, Nov 24
Fri, Nov 1
Sat, Oct 26
Sat, Oct 5
Fri, Sep 27
Fri, Sep 20
Sat, Sep 14
Fri, Sep 6
Sat, May 11
Fri, May 3
Sun, Apr 21
Sat, Apr 13
Sat, Mar 23
Fri, Mar 1
Sat, Feb 23
Sat, Feb 16
Fri, Feb 8
Fri, Jan 4
Thu, Dec 26
Fri, Nov 29
Fri, Nov 22
Sat, Nov 2
Fri, Oct 25
Sat, Oct 5
Fri, Sep 27
Fri, Sep 6
Fri, May 3
Fri, Apr 19
Fri, Apr 12
Fri, Mar 29
Fri, Mar 1
Fri, Feb 15
Sun, Feb 10
Fri, Jan 4
Thu, Dec 26
Sat, Dec 21
Sat, Nov 23
Fri, Oct 25
Fri, Sep 27
Fri, Sep 20
Sat, Sep 14
Fri, May 3
Sat, Apr 20
Sat, Mar 30
Fri, Mar 22
Fri, Mar 1
Sat, Feb 16
Fri, Feb 8
Fri, Dec 20
Sat, Nov 23
Sat, Nov 2
Fri, Oct 25
Sat, Sep 28
Sat, Sep 21
Sat, Sep 7
Sat, Apr 13
Sat, Mar 30
Fri, Mar 22
Sat, Mar 2
Fri, Feb 22
Fri, Feb 15
Fri, Jan 4
Fri, Dec 27
Fri, Nov 29
Sat, Nov 23
Sat, Sep 28
Fri, Sep 20
Fri, Sep 13
Sat, Sep 7
Fri, May 3
Fri, Apr 19
Sat, Mar 23
Sun, Feb 24
Sat, Feb 9
Sat, Jan 5
Sat, Dec 28
Sat, Nov 30
Sat, Nov 2
Fri, Oct 25
Fri, Oct 4
Fri, Apr 26
Fri, Apr 19
Sat, Mar 23
Fri, Feb 8
Sat, Dec 21
Fri, Nov 29
Fri, Sep 13
Sat, Sep 7
Fri, Apr 12
Fri, Mar 1
Fri, Feb 22
Sat, Jan 5
Thu, Dec 26
Sun, Oct 6
Fri, Sep 20
Sat, Apr 13
Fri, Feb 15
Fri, Nov 1
Fri, Sep 13
Fri, May 3
Fri, Mar 29
Fri, Oct 4
Sun, Feb 24
Fri, Dec 26
Fri, Dec 19
Sat, Nov 29
Sun, Nov 23
Fri, Oct 31
Sat, Oct 11
Sat, Oct 4
Fri, Sep 26
Fri, Sep 19
Sat, Sep 13
Sat, Sep 6
Sat, May 31
Sat, May 17
Sat, May 10
Fri, May 2
Fri, Apr 18
Fri, Apr 11
Sat, Mar 29
Fri, Mar 21
Sat, Mar 1
Thu, Feb 20
Fri, Feb 14
Sun, Feb 9
Sat, Jan 4
Sat, Dec 27
Sat, Dec 20
Sun, Nov 30
Fri, Nov 21
Fri, Oct 31
Sat, Oct 11
Sun, Oct 5
Fri, Sep 26
Sat, Sep 20
Sun, Sep 14
Fri, May 16
Sat, May 10
Fri, May 2
Sat, Apr 26
Fri, Apr 18
Sat, Apr 12
Fri, Apr 4
Fri, Mar 28
Sat, Mar 22
Sun, Feb 23
Sat, Feb 15
Sun, Feb 9
Fri, Nov 28
Fri, Nov 21
Sat, Nov 1
Fri, Oct 10
Sat, Sep 27
Fri, Sep 19
Fri, Sep 12
Fri, Sep 5
Sat, May 10
Sat, May 3
Sat, Apr 19
Sat, Mar 22
Sat, Mar 1
Sun, Feb 23
Sat, Feb 15
Sat, Feb 8
Fri, Jan 3
Fri, Dec 26
Sat, Dec 20
Fri, Nov 21
Sat, Nov 1
Fri, Oct 3
Sat, Sep 27
Fri, Sep 19
Fri, Sep 12
Sat, Sep 6
Fri, Apr 11
Sat, Mar 29
Fri, Mar 21
Fri, Mar 14
Fri, Feb 28
Sun, Feb 23
Fri, Feb 7
Sat, Dec 27
Fri, Oct 31
Sun, Oct 12
Fri, Oct 3
Sun, Sep 21
Fri, Sep 12
Fri, Sep 5
Sat, May 10
Thu, May 1
Sun, Apr 20
Fri, Mar 21
Fri, Feb 28
Sun, Feb 16
Fri, Jan 3
Fri, Dec 19
Sat, Nov 29
Sat, Nov 1
Sun, Oct 5
Fri, Sep 26
Sat, Sep 20
Sat, May 10
Fri, May 2
Sun, Apr 20
Sat, Apr 12
Sun, Mar 30
Sat, Feb 22
Sat, Feb 8
Fri, Dec 26
Fri, Nov 28
Sun, Nov 23
Fri, Oct 3
Sun, Sep 7
Sat, May 3
Fri, Apr 11
Sat, Mar 1
Wed, Jan 1
Fri, Dec 19
Sat, Nov 29
Sat, Oct 11
Fri, Sep 12
Sat, Apr 19
Thu, Apr 3
Sat, Mar 29
Sat, Feb 15
Sun, Dec 21
Sun, Sep 28
Sat, Sep 6
Sat, May 10
Sat, Apr 12
Sat, Mar 29
Sun, Mar 23
Fri, Nov 21
Fri, Oct 10
Sat, Mar 1
Sun, Feb 23
Sun, Dec 28
Sat, Jan 4
Sun, Dec 27
Fri, Nov 27
Sat, Nov 7
Sun, Nov 1
Fri, Oct 23
Fri, Oct 16
Fri, Oct 2
Fri, Sep 11
Sat, Sep 5
Sat, May 30
Fri, May 22
Sat, May 16
Fri, May 8
Sat, Apr 25
Fri, Apr 10
Fri, Mar 27
Fri, Mar 6
Sat, Feb 28
Sat, Feb 21
Sun, Feb 15
Fri, Jan 9
Fri, Jan 2
Sun, Dec 27
Sun, Dec 6
Sat, Nov 28
Sat, Nov 7
Fri, Oct 30
Fri, Oct 23
Sat, Oct 17
Sun, Sep 13
Sat, Sep 5
Sat, May 23
Sat, May 16
Sat, May 9
Sat, Apr 25
Sat, Apr 11
Sat, Mar 28
Sat, Mar 7
Sat, Feb 21
Sat, Feb 14
Sat, Jan 10
Thu, Jan 1
Sat, Dec 26
Sun, Dec 6
Sat, Nov 28
Sat, Nov 7
Sat, Oct 24
Sat, Oct 17
Fri, Oct 2
Fri, Sep 4
Sat, May 16
Sat, Apr 25
Fri, Apr 10
Sat, Mar 28
Fri, Feb 27
Fri, Feb 13
Sun, Jan 11
Sat, Jan 3
Sat, Dec 26
Fri, Dec 4
Fri, Nov 27
Sun, Nov 8
Fri, Oct 23
Fri, Oct 16
Fri, Oct 2
Sat, Sep 12
Fri, Apr 24
Sat, Apr 11
Fri, Mar 27
Sun, Mar 8
Fri, Feb 27
Fri, Feb 20
Fri, Feb 13
Sun, Jan 11
Sat, Jan 3
Fri, Nov 6
Sun, Nov 1
Fri, Oct 16
Sat, Oct 3
Sat, Sep 12
Fri, Sep 4
Sat, May 16
Fri, May 8
Sun, Apr 12
Sat, Mar 7
Fri, Feb 20
Sun, Feb 15
Sat, Jan 10
Sat, Dec 5
Sun, Nov 29
Fri, Oct 30
Sun, Oct 4
Sat, May 16
Sun, May 10
Sat, Apr 25
Sat, Apr 11
Sat, Mar 28
Sun, Feb 15
Fri, Dec 4
Fri, Nov 6
Sat, Oct 31
Fri, Oct 16
Sat, Oct 3
Fri, Sep 4
Sat, May 9
Fri, Mar 6
Sun, Mar 1
Sun, Feb 22
Fri, Jan 9
Fri, Nov 27
Sat, Oct 24
Sat, Sep 12
Fri, May 8
Fri, Apr 24
Sat, Mar 7
Sun, Mar 1
Sun, Dec 27
Fri, Oct 23
Fri, Sep 11
Sat, Mar 28
Sun, Mar 1
Thu, Jan 1
Sat, Oct 31
Sun, Sep 6
Sat, May 16
Fri, Feb 20
Sun, Dec 27
Sat, Jan 3
Sat, Dec 31
Mon, Dec 26
Sat, Dec 3
Fri, Nov 25
Sat, Nov 5
Sat, Oct 29
Sat, Oct 8
Sat, Oct 1
Fri, Sep 23
Fri, Sep 16
Sat, Sep 10
Fri, Sep 2
Sat, May 28
Fri, May 20
Sat, May 7
Sat, Apr 30
Fri, Apr 15
Sat, Apr 2
Sat, Mar 26
Fri, Mar 18
Sat, Mar 5
Sun, Feb 28
Sat, Feb 20
Fri, Feb 12
Fri, Jan 29
Fri, Jan 8
Fri, Jan 1
Sat, Dec 31
Fri, Dec 23
Sat, Dec 3
Fri, Nov 25
Fri, Nov 4
Fri, Oct 7
Fri, Sep 30
Sat, Sep 24
Sat, Sep 10
Sat, Sep 3
Sat, May 21
Sat, May 7
Fri, Apr 29
Sat, Apr 16
Fri, Apr 1
Fri, Mar 4
Sat, Feb 27
Sat, Feb 20
Thu, Feb 11
Sat, Jan 30
Sun, Jan 10
Sat, Dec 31
Mon, Dec 26
Fri, Dec 2
Fri, Nov 25
Sat, Nov 5
Fri, Oct 28
Sat, Oct 8
Fri, Sep 30
Fri, Sep 23
Fri, Sep 16
Fri, Apr 29
Sat, Apr 16
Fri, Apr 8
Sat, Apr 2
Fri, Mar 25
Sun, Mar 6
Thu, Feb 25
Fri, Feb 19
Fri, Feb 12
Sun, Jan 31
Sat, Jan 2
Sat, Dec 3
Fri, Nov 4
Fri, Oct 28
Sat, Oct 1
Fri, Sep 16
Sat, Sep 10
Fri, Sep 2
Sat, May 7
Sat, Apr 16
Fri, Mar 4
Sun, Feb 28
Sun, Feb 21
Fri, Feb 5
Sat, Jan 30
Sat, Jan 2
Tue, Dec 27
Sat, Dec 3
Fri, Oct 28
Sat, Oct 8
Sat, Oct 1
Fri, Sep 9
Sat, Sep 3
Sat, May 7
Sat, Apr 30
Sat, Apr 2
Sat, Mar 26
Fri, Mar 4
Sun, Feb 28
Fri, Feb 12
Fri, Jan 1
Sat, Nov 26
Fri, Nov 4
Sat, Oct 1
Sat, Sep 24
Sat, Sep 17
Fri, Sep 9
Fri, Apr 29
Fri, Mar 25
Fri, Mar 18
Sat, Mar 5
Sun, Feb 28
Sun, Feb 14
Sat, Jan 30
Mon, Dec 26
Fri, Nov 4
Fri, Oct 7
Sat, Sep 24
Sat, Sep 3
Sat, May 7
Sat, Apr 30
Sun, Apr 17
Fri, Mar 25
Sat, Feb 13
Sat, Jan 30
Fri, Dec 2
Sat, Oct 29
Sat, Sep 17
Fri, Sep 2
Fri, Apr 15
Fri, Apr 1
Fri, Feb 19
Fri, Jan 1
Sat, Dec 31
Sun, Nov 27
Fri, Oct 28
Fri, Oct 7
Fri, Apr 1
Sun, Mar 27
Fri, Jan 8
Fri, Sep 23
Fri, Sep 9
Sat, May 7
Fri, Feb 19
Fri, Dec 23
Sun, Jan 3
Tue, Dec 26
Sat, Dec 2
Sun, Nov 26
Fri, Nov 3
Fri, Oct 27
Sat, Oct 7
Sat, Sep 30
Fri, Sep 22
Sat, Sep 16
Sat, Sep 9
Fri, Sep 1
Sat, May 27
Sat, May 20
Sat, May 6
Sat, Apr 29
Sat, Apr 15
Sat, Apr 8
Sat, Mar 25
Sat, Mar 4
Fri, Feb 24
Sat, Feb 18
Fri, Feb 10
Fri, Feb 3
Sat, Dec 2
Fri, Nov 24
Fri, Nov 3
Sat, Oct 28
Fri, Sep 29
Fri, Sep 22
Sat, Sep 16
Fri, Sep 8
Sat, Sep 2
Fri, May 19
Sat, May 6
Fri, Apr 28
Sat, Apr 15
Sat, Apr 8
Sat, Mar 25
Sat, Mar 4
Fri, Feb 24
Fri, Feb 17
Sun, Feb 12
Fri, Jan 6
Sun, Dec 31
Tue, Dec 26
Sat, Dec 2
Sun, Nov 26
Fri, Nov 3
Sat, Oct 28
Sat, Oct 7
Fri, Sep 29
Sat, Sep 23
Fri, Sep 15
Sat, Sep 9
Sat, Sep 2
Sat, May 6
Sat, Apr 29
Sat, Apr 15
Sat, Apr 8
Fri, Mar 24
Fri, Feb 17
Fri, Feb 10
Fri, Jan 6
Sun, Jan 1
Tue, Dec 26
Sat, Dec 23
Fri, Dec 1
Fri, Nov 24
Sat, Nov 4
Fri, Oct 6
Sat, Sep 30
Fri, Sep 22
Sat, Sep 9
Fri, Sep 1
Sat, Apr 29
Fri, Apr 7
Fri, Mar 24
Sat, Mar 11
Fri, Mar 3
Sun, Feb 26
Sat, Feb 18
Fri, Feb 10
Sat, Dec 30
Sat, Dec 23
Fri, Dec 1
Sun, Nov 26
Fri, Oct 27
Fri, Oct 6
Fri, Sep 29
Sat, Sep 16
Sat, Sep 9
Sat, Sep 2
Sat, May 6
Fri, Apr 14
Sat, Mar 25
Sat, Mar 4
Sun, Feb 26
Sat, Jan 7
Tue, Dec 26
Fri, Nov 24
Sat, Nov 4
Fri, Oct 6
Sat, Sep 23
Fri, Sep 1
Sat, May 6
Fri, Apr 28
Sat, Apr 15
Fri, Feb 24
Sat, Feb 18
Sun, Feb 12
Sat, Dec 2
Sat, Nov 4
Fri, Sep 15
Sat, Sep 9
Fri, Apr 7
Sat, Apr 1
Fri, Mar 3
Sun, Feb 26
Sat, Feb 18
Sat, Jan 7
Fri, Dec 1
Fri, Nov 24
Sat, Nov 4
Sat, Oct 28
Fri, Oct 6
Fri, Sep 15
Fri, Sep 8
Fri, Apr 28
Sat, Apr 15
Fri, Mar 3
Sat, Dec 30
Sat, Dec 23
Sat, Oct 7
Fri, Sep 22
Sat, May 6
Sat, Mar 25
Fri, Jan 6
Sun, Dec 31
Fri, Oct 27
Sat, Sep 30
Sat, Apr 8
Sun, Jan 1
Sat, Oct 28
Sat, Sep 23
Sat, Sep 16
Sat, Sep 2
Fri, Feb 10
Sat, Dec 29
Sat, Dec 22
Sat, Dec 1
Fri, Nov 23
Fri, Nov 2
Sat, Oct 27
Fri, Oct 5
Sat, Sep 29
Sat, Sep 22
Sat, Sep 15
Fri, Sep 7
Sat, Sep 1
Fri, May 18
Sat, Apr 28
Sat, Apr 21
Fri, Apr 13
Sat, Apr 7
Fri, Mar 23
Fri, Feb 23
Fri, Feb 16
Fri, Feb 9
Sat, Jan 6
Sat, Dec 29
Fri, Dec 21
Fri, Nov 30
Sun, Nov 25
Sun, Nov 4
Sat, Oct 6
Sat, Sep 29
Fri, Sep 21
Fri, Sep 14
Sat, Sep 1
Sat, May 19
Sat, May 5
Sat, Apr 28
Fri, Apr 13
Sat, Apr 7
Sat, Mar 24
Fri, Mar 16
Sat, Feb 17
Sat, Feb 10
Sat, Jan 6
Mon, Jan 1
Sat, Dec 1
Sat, Nov 24
Sat, Oct 27
Fri, Oct 5
Fri, Sep 28
Fri, Sep 21
Sat, Sep 8
Sat, May 5
Sat, Apr 28
Sat, Apr 7
Fri, Mar 23
Sat, Mar 3
Sat, Feb 24
Sat, Feb 10
Sat, Jan 20
Sat, Jan 13
Sat, Jan 6
Sat, Dec 29
Fri, Dec 21
Sat, Dec 1
Sun, Nov 4
Sat, Oct 6
Sat, Sep 15
Sat, Sep 8
Fri, Aug 31
Sat, Apr 28
Sat, Apr 14
Sat, Mar 24
Fri, Mar 16
Sun, Feb 25
Sat, Jan 6
Sun, Dec 30
Sat, Dec 22
Fri, Nov 30
Fri, Nov 23
Fri, Oct 26
Sat, Oct 6
Sat, Sep 29
Sat, Sep 22
Fri, Aug 31
Sun, May 20
Sat, Apr 21
Fri, Apr 13
Fri, Apr 6
Sat, Mar 24
Fri, Feb 16
Fri, Feb 9
Fri, Dec 28
Sat, Dec 22
Sun, Nov 25
Sat, Nov 3
Fri, Oct 5
Sat, Sep 29
Sat, Sep 22
Fri, Sep 14
Sat, Sep 8
Sat, Apr 28
Fri, Mar 23
Sat, Feb 24
Fri, Feb 16
Mon, Jan 1
Sat, Dec 29
Sun, Dec 23
Sat, Dec 22
Fri, Oct 26
Sat, Sep 22
Fri, Aug 31
Sat, Apr 28
Sat, Apr 14
Sat, Apr 7
Sat, Dec 28
Sat, Dec 21
Sat, Nov 30
Sat, Nov 9
Fri, Nov 1
Sat, Oct 26
Sat, Oct 12
Fri, Oct 4
Fri, Sep 27
Sat, May 25
Fri, May 17
Sat, Apr 27
Sat, Apr 13
Fri, Apr 5
Sat, Mar 23
Sat, Mar 2
Fri, Feb 22
Sat, Feb 16
Fri, Jan 25
Sat, Jan 5
Sat, Dec 28
Sat, Dec 21
Fri, Nov 29
Sat, Nov 9
Sat, Nov 2
Fri, Oct 25
Fri, Oct 11
Sat, Oct 5
Sat, Sep 28
Sat, May 18
Sat, May 4
Sat, Apr 27
Fri, Apr 12
Fri, Apr 5
Sat, Mar 23
Sat, Mar 2
Fri, Feb 22
Fri, Feb 15
Sat, Jan 26
Sat, Jan 5
Fri, Dec 27
Sat, Nov 30
Fri, Nov 8
Sat, Nov 2
Sat, Oct 26
Fri, Oct 11
Sat, Oct 5
Sat, Sep 28
Sat, May 4
Sat, Apr 13
Sat, Apr 6
Fri, Mar 22
Sat, Mar 2
Sat, Feb 16
Sat, Jan 26
Thu, Dec 26
Sat, Dec 21
Sat, Nov 30
Sat, Nov 9
Sat, Oct 12
Fri, Oct 4
Fri, Sep 27
Sat, May 18
Sat, Apr 27
Fri, Apr 12
Sat, Apr 6
Sat, Mar 23
Fri, Feb 15
Sat, Jan 5
Thu, Dec 26
Sat, Nov 30
Sat, Nov 9
Fri, Oct 25
Sat, Oct 5
Sat, Sep 28
Fri, Mar 22
Sat, Mar 2
Sat, Feb 23
Sat, Nov 2
Sat, Oct 5
Sat, Apr 27
Sat, Apr 13
Fri, Mar 1
Sun, Feb 24
Sat, Feb 2
Sat, Jan 26
Fri, Jan 18
Sun, Jan 6
Sat, Dec 28
Sat, Dec 21
Sat, Nov 30
Fri, Nov 1
Sat, Oct 26
Sat, Oct 12
Sat, Oct 5
Sat, Sep 28
Sat, Apr 27
Sat, Apr 13
Sat, Feb 23
Sat, Feb 16

0     2011-12-30
1     2011-12-26
2     2011-12-03
3     2011-11-26
4     2011-11-04
         ...
95    2019-09-28
96    2019-04-27
97    2019-04-13
98    2019-02-23
99    2019-02-16
Name: date_formatted, Length: 1197, dtype: object

In [35]:
t14_file_path = 'formed_data/game_data_v2/T14_game_data_v2'
urc_file_path = 'formed_data/game_data_v2/URC_game_data_v2'

# run_joiner_output(sched_files_use_t14, game_files_use_t14, t14_file_path)
run_joiner_output(sched_files_use_urc, game_files_use_urc, urc_file_path)

DF for season 2010-2011 saved to formed_data/game_data_v2/URC_game_data_v2_2010-2011.csv
DF for season 2011-2012 saved to formed_data/game_data_v2/URC_game_data_v2_2011-2012.csv
DF for season 2012-2013 saved to formed_data/game_data_v2/URC_game_data_v2_2012-2013.csv
DF for season 2013-2014 saved to formed_data/game_data_v2/URC_game_data_v2_2013-2014.csv
DF for season 2014-2015 saved to formed_data/game_data_v2/URC_game_data_v2_2014-2015.csv
DF for season 2015-2016 saved to formed_data/game_data_v2/URC_game_data_v2_2015-2016.csv
DF for season 2016-2017 saved to formed_data/game_data_v2/URC_game_data_v2_2016-2017.csv
DF for season 2017-2018 saved to formed_data/game_data_v2/URC_game_data_v2_2017-2018.csv
DF for season 2018-2019 saved to formed_data/game_data_v2/URC_game_data_v2_2018-2019.csv
DF for season 2019-2020 saved to formed_data/game_data_v2/URC_game_data_v2_2019-2020.csv

In [33]:
def test_func(date_parse):
    try:
        dow = date_parse[:date_parse.find(',')]
        month = date_parse[date_parse.find(',')+2:date_parse.find(',')+5]
        month_num = datetime.datetime.strptime(month, '%b').month
        # return month_num
    except:
        print(date_parse)
        return 'error'

In [19]:
urc_sched_df = pd.concat(list(map(pd.read_csv, urc_sched_files)))

In [20]:
urc_sched_df

,Unnamed: 0,date,home_team,away_team,home_team_abbr,away_team_abbr,game_link,score,home_score,away_score,competition,stadium,game_id,league_id,season
0,0,"Fri, Dec 3",Leinster,Connacht,LEI,CON,/rugby/match/_/gameId/594385/league/270557,47 - 19,47,19,United Rugby Championship,"RDS Arena, Dublin",594385.0,270557.0,2021
1,1,"Sat, Nov 27",Leinster,Ulster,LEI,ULS,/rugby/match/_/gameId/594381/league/270557,10 - 20,10,20,United Rugby Championship,"RDS Arena, Dublin",594381.0,270557.0,2021
2,2,"Fri, Oct 22",Glasgow Warriors,Leinster,GLA,LEI,/rugby/match/_/gameId/594369/league/270557,15 - 31,15,31,United Rugby Championship,"Scotstoun Stadium, Glasgow",594369.0,270557.0,2021
3,3,"Sat, Oct 16",Leinster,Scarlets,LEI,SCA,/rugby/match/_/gameId/594364/league/270557,50 - 15,50,15,United Rugby Championship,"RDS Arena, Dublin",594364.0,270557.0,2021
4,4,"Sat, Oct 9",Leinster,Zebre,LEI,ZEB,/rugby/match/_/gameId/594353/league/270557,43 - 7,43,7,United Rugby Championship,"RDS Arena, Dublin",594353.0,270557.0,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,214,"Sat, Oct 28",Ospreys,Zebre,OSP,ZEB,/rugby/match/_/gameId/597934/league/270557,34 - 31,34,31,United Rugby Championship,"Swansea.com Stadium, Swansea",597934.0,270557.0,2023
132,218,"Sat, Mar 25",Ospreys,Dragons,OSP,DRA,/rugby/match/_/gameId/599506/league/270557,37 - 18,37,18,United Rugby Championship,"Swansea.com Stadium, Swansea",599506.0,270557.0,2023
133,221,"Sun, Jan 29",Zebre,Ospreys,ZEB,OSP,/rugby/match/_/gameId/599483/league/270557,24 - 28,24,28,United Rugby Championship,"Stadio Sergio Lanfranchi, Parma",599483.0,270557.0,2023
134,232,"Sat, Apr 22",Dragons,Scarlets,DRA,SCA,/rugby/match/_/gameId/599523/league/270557,31 - 14,31,14,United Rugby Championship,"Principality Stadium, Cardiff",599523.0,270557.0,2023
135,239,"Sun, Jan 1",Scarlets,Dragons,SCA,DRA,/rugby/match/_/gameId/599465/league/270557,33 - 17,33,17,United Rugby Championship,"Parc y Scarlets, Llanelli",599465.0,270557.0,2023

In [27]:
t14_sched_df['date'].isnull().sum()

np.int64(0)

In [34]:
import dateparser

ModuleNotFoundError: No module named 'dateparser'

In [32]:
t14_sched_df

,Unnamed: 0,date,home_team,away_team,home_team_abbr,away_team_abbr,game_link,score,home_score,away_score,competition,stadium,game_id,league_id,season
0,0,"Sat, Dec 4",Bordeaux Begles,Stade Toulousain,UNI,STA,/rugby/match/_/gameId/594117/league/270559,17 - 7,17,7,French Top 14,"Stade Chaban-Delmas, Bordeaux",594117.0,270559.0,2021
1,1,"Sat, Nov 27",Stade Toulousain,Brive,STA,BRIV,/rugby/match/_/gameId/594114/league/270559,18 - 11,18,11,French Top 14,"Stade Ernest-Wallon, Toulouse",594114.0,270559.0,2021
2,2,"Sat, Nov 6",Stade Toulousain,Perpignan,STA,USA,/rugby/match/_/gameId/594108/league/270559,37 - 15,37,15,French Top 14,"Stade Ernest-Wallon, Toulouse",594108.0,270559.0,2021
3,3,"Sun, Oct 31",Racing 92,Stade Toulousain,RAC,STA,/rugby/match/_/gameId/594098/league/270559,27 - 18,27,18,French Top 14,"Paris La Defense Arena, Nanterre",594098.0,270559.0,2021
4,4,"Sat, Oct 23",Stade Toulousain,Castres Olympique,STA,CAS,/rugby/match/_/gameId/594094/league/270559,41 - 0,41,0,French Top 14,"Stade Ernest-Wallon, Toulouse",594094.0,270559.0,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,308,"Sat, Oct 5",Agen,Bayonne,AGN,BAY,NaN,27 - 29,27,29,French Top 14,"Alfred Armandie, Agen",NaN,NaN,2019
184,312,"Sat, Aug 31",Agen,Brive,AGN,BRIV,NaN,16 - 10,16,10,French Top 14,"Alfred Armandie, Agen",NaN,NaN,2019
185,316,"Sat, May 4",Grenoble,Agen,GRENO,AGN,/rugby/match/_/gameId/293211/league/270559,11 - 29,11,29,French Top 14,"Stade des Alpes, Grenoble",293211.0,270559.0,2019
186,323,"Sat, Feb 23",Perpignan,Agen,USA,AGN,/rugby/match/_/gameId/293157/league/270559,13 - 20,13,20,French Top 14,"Stade Aime Giral, Perpignan",293157.0,270559.0,2019
187,333,"Sat, Mar 23",Perpignan,Grenoble,USA,GRENO,/rugby/match/_/gameId/293180/league/270559,22 - 16,22,16,French Top 14,"Stade Aime Giral, Perpignan",293180.0,270559.0,2019

In [31]:
for i in range(len(t14_sched_df)):
    test_func(t14_sched_df['date'].iloc[i])

Jue, Abr 29
Vie, Abr 16
Vie, Ene 22
Sáb, Ene 16
Sáb, Dic 31
Vie, Dic 23
Sáb, Dic 3
Sáb, Abr 30
Sáb, Abr 23
Sáb, Abr 2
Sáb, Ene 29
Sáb, Ene 8
Sáb, Ene 1

In [13]:
tester = t14_sched_df['date'].iloc[0]
tester

'Sat, Dec 4'

In [21]:
tester[tester.find(',')+2:-6]

''

In [22]:
tester

'Sat, Dec 4'

In [23]:
tester[:tester.find('.')]

'Sat, Dec '

In [24]:
tester[tester.find(',')+2:tester.find(',')+5]

'Dec'

In [25]:
datetime.datetime.strptime(tester[tester.find(',')+2:tester.find(',')+5], '%b').month

12

In [26]:
tester[tester.find(tester[tester.find(',')+2:tester.find(',')+5])+4:]

'4'

In [ ]:
dow = date_parse[:date_parse.find(',')]
month = date_parse[date_parse.find(',')+2:date_parse.find(',')+5]
month_num = datetime.datetime.strptime(month, '%b').month
dom = date_parse[date_parse.find(month)+4:]

In [12]:
t14_sched_df = pd.concat(list(map(pd.read_csv, t14_sched_files)))
t14_sched_df

,Unnamed: 0,date,home_team,away_team,home_team_abbr,away_team_abbr,game_link,score,home_score,away_score,competition,stadium,game_id,league_id,season
0,0,"Sat, Dec 4",Bordeaux Begles,Stade Toulousain,UNI,STA,/rugby/match/_/gameId/594117/league/270559,17 - 7,17,7,French Top 14,"Stade Chaban-Delmas, Bordeaux",594117.0,270559.0,2021
1,1,"Sat, Nov 27",Stade Toulousain,Brive,STA,BRIV,/rugby/match/_/gameId/594114/league/270559,18 - 11,18,11,French Top 14,"Stade Ernest-Wallon, Toulouse",594114.0,270559.0,2021
2,2,"Sat, Nov 6",Stade Toulousain,Perpignan,STA,USA,/rugby/match/_/gameId/594108/league/270559,37 - 15,37,15,French Top 14,"Stade Ernest-Wallon, Toulouse",594108.0,270559.0,2021
3,3,"Sun, Oct 31",Racing 92,Stade Toulousain,RAC,STA,/rugby/match/_/gameId/594098/league/270559,27 - 18,27,18,French Top 14,"Paris La Defense Arena, Nanterre",594098.0,270559.0,2021
4,4,"Sat, Oct 23",Stade Toulousain,Castres Olympique,STA,CAS,/rugby/match/_/gameId/594094/league/270559,41 - 0,41,0,French Top 14,"Stade Ernest-Wallon, Toulouse",594094.0,270559.0,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,308,"Sat, Oct 5",Agen,Bayonne,AGN,BAY,NaN,27 - 29,27,29,French Top 14,"Alfred Armandie, Agen",NaN,NaN,2019
184,312,"Sat, Aug 31",Agen,Brive,AGN,BRIV,NaN,16 - 10,16,10,French Top 14,"Alfred Armandie, Agen",NaN,NaN,2019
185,316,"Sat, May 4",Grenoble,Agen,GRENO,AGN,/rugby/match/_/gameId/293211/league/270559,11 - 29,11,29,French Top 14,"Stade des Alpes, Grenoble",293211.0,270559.0,2019
186,323,"Sat, Feb 23",Perpignan,Agen,USA,AGN,/rugby/match/_/gameId/293157/league/270559,13 - 20,13,20,French Top 14,"Stade Aime Giral, Perpignan",293157.0,270559.0,2019
187,333,"Sat, Mar 23",Perpignan,Grenoble,USA,GRENO,/rugby/match/_/gameId/293180/league/270559,22 - 16,22,16,French Top 14,"Stade Aime Giral, Perpignan",293180.0,270559.0,2019

In [10]:
urc_file_path = 'formed_data/game_data_v2/URC_game_data_v2'
prem_file_path = 'formed_data/game_data_v2/Prem_game_data_v2'
sr_file_path = 'formed_data/game_data_v2/SR_game_data_v2'

# run_joiner_output(urc_sched_files, urc_game_files, urc_file_path)
# run_joiner_output(prem_sched_files, prem_game_files, prem_file_path)
run_joiner_output(sr_sched_files, sr_game_files, sr_file_path)

DF for season 2020 saved to formed_data/game_data_v2/SR_game_data_v2_2020.csv
DF for season 2022 saved to formed_data/game_data_v2/SR_game_data_v2_2022.csv
DF for season 2023 saved to formed_data/game_data_v2/SR_game_data_v2_2023.csv
DF for season 2024 saved to formed_data/game_data_v2/SR_game_data_v2_2024.csv

In [4]:
df_rev = pd.read_csv('formed_data/game_data_v2/URC_game_data_v2_2019-2020.csv')
df_rev.head()

,game_id,league_id,home_team,home_team_score,away_team,away_team_score,home_tries,away_tries,home_conversions,away_conversions,...,away_mauls_won_total_num,away_mauls_won_percent,away_scrum_num,away_scrum_total_num,away_scrum_won_percent,away_lineout_num,away_lineout_total_num,away_lineout_won_percent,date_formatted,league_season
0,592889,270557,Ulster,10,Leinster,28,1.0,3.0,1.0,2.0,...,7.0,1.0,6.0,6.0,1.00,14.0,14.0,1.00,2020-08-29,2019-2020
1,592884,270557,Leinster,27,Munster,25,3.0,3.0,3.0,2.0,...,10.0,0.9,4.0,4.0,1.00,13.0,13.0,1.00,2020-08-22,2019-2020
2,294787,270557,Leinster,55,Glasgow Warriors,19,9.0,3.0,5.0,2.0,...,4.0,1.0,8.0,8.0,1.00,5.0,6.0,0.83,2020-02-28,2019-2020
3,294781,270557,Ospreys,13,Leinster,21,1.0,3.0,1.0,3.0,...,5.0,1.0,12.0,12.0,1.00,9.0,13.0,0.69,2020-02-21,2019-2020
4,294775,270557,Leinster,36,Cheetahs,12,5.0,2.0,4.0,1.0,...,4.0,1.0,11.0,12.0,0.91,10.0,11.0,0.90,2020-02-15,2019-2020

In [5]:
df_rev.columns

Index(['game_id', 'league_id', 'home_team', 'home_team_score', 'away_team',
       'away_team_score', 'home_tries', 'away_tries', 'home_conversions',
       'away_conversions', 'home_penalty_goals', 'away_penalty_goals',
       'home_kick_percent', 'away_kick_percent', 'home_total_meters',
       'away_total_meters', 'home_kfh', 'away_kfh', 'home_pass_meters',
       'away_pass_meters', 'home_runs', 'away_runs', 'home_possession_1h_2h',
       'home_territory_1h_2h', 'home_clean_breaks', 'home_defenders_beaten',
       'home_offloads', 'home_rucks_won', 'home_mauls_won',
       'home_turnovers_conceeded', 'away_possession_1h_2h',
       'away_territory_1h_2h', 'away_clean_breaks', 'away_defenders_beaten',
       'away_offloads', 'away_rucks_won', 'away_mauls_won',
       'away_turnovers_conceeded', 'home_total_possession',
       'home_total_territory', 'away_total_possesion', 'away_total_territory',
       'home_scrum', 'home_lineout', 'away_scrum', 'away_lineout',
       'home_tackles', 'home_tackle_perc', 'away_tackles', 'away_tackle_perc',
       'home_red_cards', 'home_yellow_cards', 'home_free_kicks_con',
       'away_red_cards', 'away_yellow_cards', 'away_free_kicks_con',
       'home_penalties', 'away_penalties', 'date', 'competition', 'season',
       'stadium', 'home_1h_poss', 'home_2h_poss', 'home_1h_terr',
       'home_2h_terr', 'home_rucks_won_num', 'home_rucks_won_total_num',
       'home_rucks_won_percent', 'home_mauls_won_num',
       'home_mauls_won_total_num', 'home_mauls_won_percent', 'home_scrum_num',
       'home_scrum_total_num', 'home_scrum_won_percent', 'home_lineout_num',
       'home_lineout_total_num', 'home_lineout_won_percent', 'away_1h_poss',
       'away_2h_poss', 'away_1h_terr', 'away_2h_terr', 'away_rucks_won_num',
       'away_rucks_won_total_num', 'away_rucks_won_percent',
       'away_mauls_won_num', 'away_mauls_won_total_num',
       'away_mauls_won_percent', 'away_scrum_num', 'away_scrum_total_num',
       'away_scrum_won_percent', 'away_lineout_num', 'away_lineout_total_num',
       'away_lineout_won_percent', 'date_formatted', 'league_season'],
      dtype='object')

In [8]:
grouped_df = urc_test.groupby('league_season')
df_dict = {name: group for name, group in grouped_df}

In [10]:
for key, value in df_dict.items():
    print(key)

2019-2020
2020-2021
2021-2022
2022-2023
2023-2024

In [9]:
df_dict['2019-2020']

,game_id,league_id,home_team,home_team_score,away_team,away_team_score,home_tries,away_tries,home_conversions,away_conversions,...,away_mauls_won_total_num,away_mauls_won_percent,away_scrum_num,away_scrum_total_num,away_scrum_won_percent,away_lineout_num,away_lineout_total_num,away_lineout_won_percent,date_formatted,league_season
413,592889,270557,Ulster,10,Leinster,28,1.0,3.0,1.0,2.0,...,7.0,1.00,6.0,6.0,1.00,14.0,14.0,1.00,2020-08-29,2019-2020
414,592884,270557,Leinster,27,Munster,25,3.0,3.0,3.0,2.0,...,10.0,0.90,4.0,4.0,1.00,13.0,13.0,1.00,2020-08-22,2019-2020
415,294787,270557,Leinster,55,Glasgow Warriors,19,9.0,3.0,5.0,2.0,...,4.0,1.00,8.0,8.0,1.00,5.0,6.0,0.83,2020-02-28,2019-2020
416,294781,270557,Ospreys,13,Leinster,21,1.0,3.0,1.0,3.0,...,5.0,1.00,12.0,12.0,1.00,9.0,13.0,0.69,2020-02-21,2019-2020
417,294775,270557,Leinster,36,Cheetahs,12,5.0,2.0,4.0,1.0,...,4.0,1.00,11.0,12.0,0.91,10.0,11.0,0.90,2020-02-15,2019-2020
418,294771,270557,Leinster,54,Connacht,7,8.0,1.0,7.0,1.0,...,3.0,1.00,5.0,5.0,1.00,10.0,13.0,0.76,2020-01-04,2019-2020
429,592886,270557,Connacht,26,Ulster,20,4.0,2.0,3.0,2.0,...,3.0,0.66,13.0,13.0,1.00,11.0,15.0,0.73,2020-08-23,2019-2020
430,294784,270557,Ulster,20,Cheetahs,10,2.0,1.0,2.0,1.0,...,6.0,1.00,1.0,1.0,1.00,17.0,20.0,0.85,2020-02-22,2019-2020
431,294777,270557,Ospreys,26,Ulster,24,3.0,3.0,1.0,3.0,...,6.0,0.83,4.0,4.0,1.00,12.0,14.0,0.85,2020-02-15,2019-2020
432,294766,270557,Ulster,38,Munster,17,5.0,2.0,5.0,2.0,...,2.0,1.00,6.0,6.0,1.00,9.0,10.0,0.90,2020-01-03,2019-2020
439,592887,270557,Edinburgh,3,Glasgow Warriors,15,0.0,2.0,0.0,1.0,...,5.0,0.80,6.0,7.0,0.85,12.0,12.0,1.00,2020-08-28,2019-2020
440,592883,270557,Glasgow Warriors,15,Edinburgh,30,2.0,3.0,1.0,3.0,...,6.0,1.00,5.0,5.0,1.00,16.0,19.0,0.84,2020-08-22,2019-2020
441,294783,270557,Glasgow Warriors,34,Dragons,19,5.0,3.0,3.0,2.0,...,6.0,0.50,10.0,11.0,0.90,9.0,9.0,1.00,2020-02-22,2019-2020
442,294773,270557,Glasgow Warriors,56,Zebre,24,7.0,3.0,7.0,3.0,...,3.0,1.00,8.0,8.0,1.00,10.0,10.0,1.00,2020-02-14,2019-2020
443,294768,270557,Benetton Treviso,19,Glasgow Warriors,38,3.0,6.0,2.0,4.0,...,3.0,0.66,6.0,7.0,0.85,6.0,7.0,0.85,2020-01-04,2019-2020
444,294792,270557,Dragons,13,Cheetahs,10,1.0,1.0,1.0,1.0,...,11.0,0.72,5.0,7.0,0.71,16.0,18.0,0.88,2020-02-29,2019-2020
445,294765,270557,Cheetahs,45,Southern Kings,0,7.0,0.0,5.0,0.0,...,5.0,1.00,10.0,11.0,0.90,12.0,15.0,0.80,2020-02-01,2019-2020
446,294758,270557,Southern Kings,30,Cheetahs,31,3.0,5.0,3.0,3.0,...,5.0,1.00,4.0,4.0,1.00,15.0,17.0,0.88,2020-01-25,2019-2020
447,294769,270557,Zebre,41,Cheetahs,13,5.0,2.0,5.0,0.0,...,5.0,0.80,7.0,7.0,1.00,9.0,11.0,0.81,2020-01-04,2019-2020
452,592888,270557,Dragons,20,Scarlets,41,3.0,6.0,1.0,4.0,...,9.0,1.00,8.0,9.0,0.88,17.0,19.0,0.89,2020-08-29,2019-2020
453,592885,270557,Ospreys,20,Dragons,20,2.0,3.0,2.0,1.0,...,9.0,1.00,3.0,3.0,1.00,22.0,26.0,0.84,2020-08-23,2019-2020
454,294779,270557,Dragons,25,Benetton Treviso,37,3.0,4.0,2.0,4.0,...,6.0,1.00,3.0,3.0,1.00,12.0,12.0,1.00,2020-03-06,2019-2020
455,294770,270557,Dragons,25,Ospreys,18,3.0,2.0,2.0,1.0,...,5.0,1.00,3.0,4.0,0.75,10.0,11.0,0.90,2020-01-04,2019-2020
461,592892,270557,Zebre,9,Benetton Treviso,16,0.0,2.0,0.0,0.0,...,12.0,0.83,9.0,10.0,0.90,16.0,18.0,0.88,2020-08-30,2019-2020
462,592881,270557,Benetton Treviso,13,Zebre,17,1.0,2.0,1.0,2.0,...,11.0,0.81,3.0,4.0,0.75,18.0,21.0,0.85,2020-08-21,2019-2020
463,294780,270557,Zebre,0,Munster,28,0.0,4.0,0.0,4.0,...,8.0,1.00,6.0,7.0,0.85,14.0,14.0,1.00,2020-02-21,2019-2020
468,592891,270557,Cardiff Blues,29,Ospreys,20,2.0,2.0,2.0,2.0,...,3.0,1.00,8.0,9.0,0.88,11.0,12.0,0.91,2020-08-30,2019-2020

In [6]:
df_dict.keys()

dict_keys(['2019-2020', '2020-2021', '2021-2022', '2022-2023', '2023-2024'])

In [4]:
urc_test.head()

,game_id,league_id,home_team,home_team_score,away_team,away_team_score,home_tries,away_tries,home_conversions,away_conversions,...,away_mauls_won_total_num,away_mauls_won_percent,away_scrum_num,away_scrum_total_num,away_scrum_won_percent,away_lineout_num,away_lineout_total_num,away_lineout_won_percent,date_formatted,league_season
0,598075,270557,Munster,10,Glasgow Warriors,17,1.0,2.0,1.0,2.0,...,5.0,1.0,11.0,14.0,0.78,9.0,12.0,0.75,2024-06-15,2023-2024
1,598070,270557,Munster,23,Ospreys,7,2.0,1.0,2.0,1.0,...,2.0,1.0,5.0,7.0,0.71,9.0,10.0,0.90,2024-06-07,2023-2024
2,598069,270557,Munster,29,Ulster,24,4.0,3.0,3.0,3.0,...,3.0,1.0,5.0,5.0,1.00,7.0,9.0,0.77,2024-06-01,2023-2024
3,598055,270557,Edinburgh,26,Munster,29,2.0,4.0,2.0,3.0,...,2.0,1.0,4.0,4.0,1.00,8.0,10.0,0.80,2024-05-17,2023-2024
4,598052,270557,Munster,47,Connacht,12,7.0,2.0,6.0,1.0,...,1.0,1.0,6.0,8.0,0.75,7.0,10.0,0.70,2024-05-11,2023-2024

In [ ]:
run_joiner_output(urc_sched_files, urc_game_files, 'game_data_v2')
run_joiner_output(prem_sched_files, prem_game_files, 'game_data_v2')
run_joiner_output(prem_sched_files, prem_game_files, 'game_data_v2')

In [3]:
urc_sched_df = pd.concat(list(map(pd.read_csv, urc_sched_files)))
urc_game_df = pd.concat(list(map(pd.read_csv, urc_game_files)))

prem_sched_df = pd.concat(list(map(pd.read_csv, prem_sched_files)))
prem_game_df = pd.concat(list(map(pd.read_csv, prem_game_files)))

prem_sched_df = pd.concat(list(map(pd.read_csv, prem_sched_files)))
prem_game_df = pd.concat(list(map(pd.read_csv, prem_game_files)))

sr_sched_df = pd.concat(list(map(pd.read_csv, sr_sched_files)))
sr_game_df = pd.concat(list(map(pd.read_csv, sr_game_files)))

In [6]:
urc_game_df.columns

Index(['game_id', 'league_id', 'home_team', 'home_team_score', 'away_team',
       'away_team_score', 'home_tries', 'away_tries', 'home_conversions',
       'away_conversions', 'home_penalty_goals', 'away_penalty_goals',
       'home_kick_percent', 'away_kick_percent', 'home_total_meters',
       'away_total_meters', 'home_kfh', 'away_kfh', 'home_pass_meters',
       'away_pass_meters', 'home_runs', 'away_runs', 'home_possession_1h_2h',
       'home_territory_1h_2h', 'home_clean_breaks', 'home_defenders_beaten',
       'home_offloads', 'home_rucks_won', 'home_mauls_won',
       'home_turnovers_conceeded', 'away_possession_1h_2h',
       'away_territory_1h_2h', 'away_clean_breaks', 'away_defenders_beaten',
       'away_offloads', 'away_rucks_won', 'away_mauls_won',
       'away_turnovers_conceeded', 'home_total_possession',
       'home_total_territory', 'away_total_possesion', 'away_total_territory',
       'home_scrum', 'home_lineout', 'away_scrum', 'away_lineout',
       'home_tackles', 'home_tackle_perc', 'away_tackles', 'away_tackle_perc',
       'home_red_cards', 'home_yellow_cards', 'home_free_kicks_con',
       'away_red_cards', 'away_yellow_cards', 'away_free_kicks_con',
       'home_penalties', 'away_penalties', 'date', 'competition', 'season',
       'stadium', 'home_1h_poss', 'home_2h_poss', 'home_1h_terr',
       'home_2h_terr', 'home_rucks_won_num', 'home_rucks_won_total_num',
       'home_rucks_won_percent', 'home_mauls_won_num',
       'home_mauls_won_total_num', 'home_mauls_won_percent', 'home_scrum_num',
       'home_scrum_total_num', 'home_scrum_won_percent', 'home_lineout_num',
       'home_lineout_total_num', 'home_lineout_won_percent', 'away_1h_poss',
       'away_2h_poss', 'away_1h_terr', 'away_2h_terr', 'away_rucks_won_num',
       'away_rucks_won_total_num', 'away_rucks_won_percent',
       'away_mauls_won_num', 'away_mauls_won_total_num',
       'away_mauls_won_percent', 'away_scrum_num', 'away_scrum_total_num',
       'away_scrum_won_percent', 'away_lineout_num', 'away_lineout_total_num',
       'away_lineout_won_percent'],
      dtype='object')

In [6]:
urc_sched_df[['month', 'day']] = urc_sched_df['date'].apply(parse_game_date_v2).apply(pd.Series)
urc_sched_df[['date', 'month', 'day']]

urc_sched_df['date_formatted'] = urc_sched_df.apply(lambda x: datetime.datetime(x['season'], x['month'], x['day']), axis=1)
urc_sched_df[['date', 'month', 'day', 'season', 'date_formatted']]

            date  month  day  season date_formatted
0     Fri, Dec 3     12    3    2021     2021-12-03
1    Sat, Nov 27     11   27    2021     2021-11-27
2    Fri, Oct 22     10   22    2021     2021-10-22
3    Sat, Oct 16     10   16    2021     2021-10-16
4     Sat, Oct 9     10    9    2021     2021-10-09
..           ...    ...  ...     ...            ...
131  Sat, Oct 28     10   28    2023     2023-10-28
132  Sat, Mar 25      3   25    2023     2023-03-25
133  Sun, Jan 29      1   29    2023     2023-01-29
134  Sat, Apr 22      4   22    2023     2023-04-22
135   Sun, Jan 1      1    1    2023     2023-01-01

[741 rows x 5 columns]

In [7]:
urc_sched_df['league_season'] = urc_sched_df.apply(assign_season, axis=1)
urc_sched_df[['date', 'month', 'day', 'season', 'date_formatted', 'league_season']]

            date  month  day  season date_formatted league_season
0     Fri, Dec 3     12    3    2021     2021-12-03     2021-2022
1    Sat, Nov 27     11   27    2021     2021-11-27     2021-2022
2    Fri, Oct 22     10   22    2021     2021-10-22     2021-2022
3    Sat, Oct 16     10   16    2021     2021-10-16     2021-2022
4     Sat, Oct 9     10    9    2021     2021-10-09     2021-2022
..           ...    ...  ...     ...            ...           ...
131  Sat, Oct 28     10   28    2023     2023-10-28     2023-2024
132  Sat, Mar 25      3   25    2023     2023-03-25     2022-2023
133  Sun, Jan 29      1   29    2023     2023-01-29     2022-2023
134  Sat, Apr 22      4   22    2023     2023-04-22     2022-2023
135   Sun, Jan 1      1    1    2023     2023-01-01     2022-2023

[741 rows x 6 columns]